/**
 * Builtin OPC UA Types
 * 
 * These types are defined by the OPC UA specification and should not be
 * generated by the code generator. They are provided by the runtime/SDK.
 * 
 * Source: OPC UA Specification Part 3 - Address Space Model
 * NodeSet Reference: Opc.Ua.NodeSet2.xml
 */

/**
 * Set of builtin type names that should be excluded from code generation
 * 
 * These are fundamental types provided by every OPC UA implementation.
 */
export const BUILTIN_TYPES = new Set<string>([
  // Base types
  'BaseDataType',
  'Number',
  'Integer',
  'UInteger',
  'Enumeration',
  
  // Primitive types
  'Boolean',
  'SByte',
  'Byte',
  'Int16',
  'UInt16',
  'Int32',
  'UInt32',
  'Int64',
  'UInt64',
  'Float',
  'Double',
  'String',
  'DateTime',
  'Guid',
  'ByteString',
  'XmlElement',
  'NodeId',
  'ExpandedNodeId',
  'StatusCode',
  'QualifiedName',
  'LocalizedText',
  'Structure',
  'DataValue',
  'Variant',
  'DiagnosticInfo',
]);

/**
 * Check if a type name is a builtin type
 * @param typeName - The BrowseName of the type to check
 * @returns true if the type is builtin and should be excluded from generation
 */
export function isBuiltinType(typeName: string): boolean {
  return BUILTIN_TYPES.has(typeName);
}
