// AUTO-GENERATED – DO NOT EDIT
import { BufferReader } from "../codecs/binary/bufferReader";
import { BufferWriter } from "../codecs/binary/bufferWriter";
import { IIdentifiable } from "../codecs/iIdentifiable";
import { ExpandedNodeId } from "../types/expandedNodeId";
import { NodeId } from "../types/nodeId";
import { BinaryEncoders } from "./binaryEncoders";
import { BinaryDecoders } from "./binaryDecoders";

export class SchemaCodec {

    private static encodeId(writer: BufferWriter, id: number): void {
        const eid = new ExpandedNodeId(NodeId.NewFourByte(0, id));
        writer.writeExpandedNodeId(eid);
    }

    public static encodeBinary(writer: BufferWriter, obj: IIdentifiable): void {
        const id = obj.id;
        SchemaCodec.encodeId(writer, id);
        switch (id) {
            case 29: BinaryEncoders.encodeEnumeration(writer, obj); break;
            case 96: BinaryEncoders.encodeRolePermissionType(writer, obj); break;
            case 97: BinaryEncoders.encodeDataTypeDefinition(writer, obj); break;
            case 99: BinaryEncoders.encodeStructureDefinition(writer, obj); break;
            case 100: BinaryEncoders.encodeEnumDefinition(writer, obj); break;
            case 101: BinaryEncoders.encodeStructureField(writer, obj); break;
            case 102: BinaryEncoders.encodeEnumField(writer, obj); break;
            case 258: BinaryEncoders.encodeNode(writer, obj); break;
            case 261: BinaryEncoders.encodeObjectNode(writer, obj); break;
            case 264: BinaryEncoders.encodeObjectTypeNode(writer, obj); break;
            case 267: BinaryEncoders.encodeVariableNode(writer, obj); break;
            case 270: BinaryEncoders.encodeVariableTypeNode(writer, obj); break;
            case 273: BinaryEncoders.encodeReferenceTypeNode(writer, obj); break;
            case 276: BinaryEncoders.encodeMethodNode(writer, obj); break;
            case 279: BinaryEncoders.encodeViewNode(writer, obj); break;
            case 282: BinaryEncoders.encodeDataTypeNode(writer, obj); break;
            case 285: BinaryEncoders.encodeReferenceNode(writer, obj); break;
            case 296: BinaryEncoders.encodeArgument(writer, obj); break;
            case 299: BinaryEncoders.encodeStatusResult(writer, obj); break;
            case 304: BinaryEncoders.encodeUserTokenPolicy(writer, obj); break;
            case 308: BinaryEncoders.encodeApplicationDescription(writer, obj); break;
            case 312: BinaryEncoders.encodeEndpointDescription(writer, obj); break;
            case 316: BinaryEncoders.encodeUserIdentityToken(writer, obj); break;
            case 322: BinaryEncoders.encodeUserNameIdentityToken(writer, obj); break;
            case 325: BinaryEncoders.encodeX509IdentityToken(writer, obj); break;
            case 331: BinaryEncoders.encodeEndpointConfiguration(writer, obj); break;
            case 338: BinaryEncoders.encodeBuildInfo(writer, obj); break;
            case 344: BinaryEncoders.encodeSignedSoftwareCertificate(writer, obj); break;
            case 349: BinaryEncoders.encodeNodeAttributes(writer, obj); break;
            case 352: BinaryEncoders.encodeObjectAttributes(writer, obj); break;
            case 355: BinaryEncoders.encodeVariableAttributes(writer, obj); break;
            case 358: BinaryEncoders.encodeMethodAttributes(writer, obj); break;
            case 361: BinaryEncoders.encodeObjectTypeAttributes(writer, obj); break;
            case 364: BinaryEncoders.encodeVariableTypeAttributes(writer, obj); break;
            case 367: BinaryEncoders.encodeReferenceTypeAttributes(writer, obj); break;
            case 370: BinaryEncoders.encodeDataTypeAttributes(writer, obj); break;
            case 373: BinaryEncoders.encodeViewAttributes(writer, obj); break;
            case 376: BinaryEncoders.encodeAddNodesItem(writer, obj); break;
            case 379: BinaryEncoders.encodeAddReferencesItem(writer, obj); break;
            case 382: BinaryEncoders.encodeDeleteNodesItem(writer, obj); break;
            case 385: BinaryEncoders.encodeDeleteReferencesItem(writer, obj); break;
            case 389: BinaryEncoders.encodeRequestHeader(writer, obj); break;
            case 392: BinaryEncoders.encodeResponseHeader(writer, obj); break;
            case 395: BinaryEncoders.encodeServiceFault(writer, obj); break;
            case 420: BinaryEncoders.encodeFindServersRequest(writer, obj); break;
            case 423: BinaryEncoders.encodeFindServersResponse(writer, obj); break;
            case 426: BinaryEncoders.encodeGetEndpointsRequest(writer, obj); break;
            case 429: BinaryEncoders.encodeGetEndpointsResponse(writer, obj); break;
            case 432: BinaryEncoders.encodeRegisteredServer(writer, obj); break;
            case 435: BinaryEncoders.encodeRegisterServerRequest(writer, obj); break;
            case 438: BinaryEncoders.encodeRegisterServerResponse(writer, obj); break;
            case 441: BinaryEncoders.encodeChannelSecurityToken(writer, obj); break;
            case 444: BinaryEncoders.encodeOpenSecureChannelRequest(writer, obj); break;
            case 447: BinaryEncoders.encodeOpenSecureChannelResponse(writer, obj); break;
            case 450: BinaryEncoders.encodeCloseSecureChannelRequest(writer, obj); break;
            case 453: BinaryEncoders.encodeCloseSecureChannelResponse(writer, obj); break;
            case 456: BinaryEncoders.encodeSignatureData(writer, obj); break;
            case 459: BinaryEncoders.encodeCreateSessionRequest(writer, obj); break;
            case 462: BinaryEncoders.encodeCreateSessionResponse(writer, obj); break;
            case 465: BinaryEncoders.encodeActivateSessionRequest(writer, obj); break;
            case 468: BinaryEncoders.encodeActivateSessionResponse(writer, obj); break;
            case 471: BinaryEncoders.encodeCloseSessionRequest(writer, obj); break;
            case 474: BinaryEncoders.encodeCloseSessionResponse(writer, obj); break;
            case 477: BinaryEncoders.encodeCancelRequest(writer, obj); break;
            case 480: BinaryEncoders.encodeCancelResponse(writer, obj); break;
            case 483: BinaryEncoders.encodeAddNodesResult(writer, obj); break;
            case 486: BinaryEncoders.encodeAddNodesRequest(writer, obj); break;
            case 489: BinaryEncoders.encodeAddNodesResponse(writer, obj); break;
            case 492: BinaryEncoders.encodeAddReferencesRequest(writer, obj); break;
            case 495: BinaryEncoders.encodeAddReferencesResponse(writer, obj); break;
            case 498: BinaryEncoders.encodeDeleteNodesRequest(writer, obj); break;
            case 501: BinaryEncoders.encodeDeleteNodesResponse(writer, obj); break;
            case 504: BinaryEncoders.encodeDeleteReferencesRequest(writer, obj); break;
            case 507: BinaryEncoders.encodeDeleteReferencesResponse(writer, obj); break;
            case 511: BinaryEncoders.encodeViewDescription(writer, obj); break;
            case 514: BinaryEncoders.encodeBrowseDescription(writer, obj); break;
            case 518: BinaryEncoders.encodeReferenceDescription(writer, obj); break;
            case 522: BinaryEncoders.encodeBrowseResult(writer, obj); break;
            case 525: BinaryEncoders.encodeBrowseRequest(writer, obj); break;
            case 528: BinaryEncoders.encodeBrowseResponse(writer, obj); break;
            case 531: BinaryEncoders.encodeBrowseNextRequest(writer, obj); break;
            case 534: BinaryEncoders.encodeBrowseNextResponse(writer, obj); break;
            case 537: BinaryEncoders.encodeRelativePathElement(writer, obj); break;
            case 540: BinaryEncoders.encodeRelativePath(writer, obj); break;
            case 543: BinaryEncoders.encodeBrowsePath(writer, obj); break;
            case 546: BinaryEncoders.encodeBrowsePathTarget(writer, obj); break;
            case 549: BinaryEncoders.encodeBrowsePathResult(writer, obj); break;
            case 552: BinaryEncoders.encodeTranslateBrowsePathsToNodeIdsRequest(writer, obj); break;
            case 555: BinaryEncoders.encodeTranslateBrowsePathsToNodeIdsResponse(writer, obj); break;
            case 558: BinaryEncoders.encodeRegisterNodesRequest(writer, obj); break;
            case 561: BinaryEncoders.encodeRegisterNodesResponse(writer, obj); break;
            case 564: BinaryEncoders.encodeUnregisterNodesRequest(writer, obj); break;
            case 567: BinaryEncoders.encodeUnregisterNodesResponse(writer, obj); break;
            case 570: BinaryEncoders.encodeQueryDataDescription(writer, obj); break;
            case 573: BinaryEncoders.encodeNodeTypeDescription(writer, obj); break;
            case 577: BinaryEncoders.encodeQueryDataSet(writer, obj); break;
            case 580: BinaryEncoders.encodeNodeReference(writer, obj); break;
            case 583: BinaryEncoders.encodeContentFilterElement(writer, obj); break;
            case 586: BinaryEncoders.encodeContentFilter(writer, obj); break;
            case 589: BinaryEncoders.encodeFilterOperand(writer, obj); break;
            case 592: BinaryEncoders.encodeElementOperand(writer, obj); break;
            case 595: BinaryEncoders.encodeLiteralOperand(writer, obj); break;
            case 598: BinaryEncoders.encodeAttributeOperand(writer, obj); break;
            case 601: BinaryEncoders.encodeSimpleAttributeOperand(writer, obj); break;
            case 604: BinaryEncoders.encodeContentFilterElementResult(writer, obj); break;
            case 607: BinaryEncoders.encodeContentFilterResult(writer, obj); break;
            case 610: BinaryEncoders.encodeParsingResult(writer, obj); break;
            case 613: BinaryEncoders.encodeQueryFirstRequest(writer, obj); break;
            case 616: BinaryEncoders.encodeQueryFirstResponse(writer, obj); break;
            case 619: BinaryEncoders.encodeQueryNextRequest(writer, obj); break;
            case 622: BinaryEncoders.encodeQueryNextResponse(writer, obj); break;
            case 626: BinaryEncoders.encodeReadValueId(writer, obj); break;
            case 629: BinaryEncoders.encodeReadRequest(writer, obj); break;
            case 632: BinaryEncoders.encodeReadResponse(writer, obj); break;
            case 635: BinaryEncoders.encodeHistoryReadValueId(writer, obj); break;
            case 638: BinaryEncoders.encodeHistoryReadResult(writer, obj); break;
            case 641: BinaryEncoders.encodeHistoryReadDetails(writer, obj); break;
            case 644: BinaryEncoders.encodeReadEventDetails(writer, obj); break;
            case 647: BinaryEncoders.encodeReadRawModifiedDetails(writer, obj); break;
            case 650: BinaryEncoders.encodeReadProcessedDetails(writer, obj); break;
            case 653: BinaryEncoders.encodeReadAtTimeDetails(writer, obj); break;
            case 656: BinaryEncoders.encodeHistoryData(writer, obj); break;
            case 659: BinaryEncoders.encodeHistoryEvent(writer, obj); break;
            case 662: BinaryEncoders.encodeHistoryReadRequest(writer, obj); break;
            case 665: BinaryEncoders.encodeHistoryReadResponse(writer, obj); break;
            case 668: BinaryEncoders.encodeWriteValue(writer, obj); break;
            case 671: BinaryEncoders.encodeWriteRequest(writer, obj); break;
            case 674: BinaryEncoders.encodeWriteResponse(writer, obj); break;
            case 677: BinaryEncoders.encodeHistoryUpdateDetails(writer, obj); break;
            case 680: BinaryEncoders.encodeUpdateDataDetails(writer, obj); break;
            case 683: BinaryEncoders.encodeUpdateEventDetails(writer, obj); break;
            case 686: BinaryEncoders.encodeDeleteRawModifiedDetails(writer, obj); break;
            case 689: BinaryEncoders.encodeDeleteAtTimeDetails(writer, obj); break;
            case 692: BinaryEncoders.encodeDeleteEventDetails(writer, obj); break;
            case 695: BinaryEncoders.encodeHistoryUpdateResult(writer, obj); break;
            case 698: BinaryEncoders.encodeHistoryUpdateRequest(writer, obj); break;
            case 701: BinaryEncoders.encodeHistoryUpdateResponse(writer, obj); break;
            case 704: BinaryEncoders.encodeCallMethodRequest(writer, obj); break;
            case 707: BinaryEncoders.encodeCallMethodResult(writer, obj); break;
            case 710: BinaryEncoders.encodeCallRequest(writer, obj); break;
            case 713: BinaryEncoders.encodeCallResponse(writer, obj); break;
            case 722: BinaryEncoders.encodeDataChangeFilter(writer, obj); break;
            case 725: BinaryEncoders.encodeEventFilter(writer, obj); break;
            case 728: BinaryEncoders.encodeAggregateFilter(writer, obj); break;
            case 734: BinaryEncoders.encodeEventFilterResult(writer, obj); break;
            case 737: BinaryEncoders.encodeAggregateFilterResult(writer, obj); break;
            case 740: BinaryEncoders.encodeMonitoringParameters(writer, obj); break;
            case 743: BinaryEncoders.encodeMonitoredItemCreateRequest(writer, obj); break;
            case 746: BinaryEncoders.encodeMonitoredItemCreateResult(writer, obj); break;
            case 749: BinaryEncoders.encodeCreateMonitoredItemsRequest(writer, obj); break;
            case 752: BinaryEncoders.encodeCreateMonitoredItemsResponse(writer, obj); break;
            case 755: BinaryEncoders.encodeMonitoredItemModifyRequest(writer, obj); break;
            case 758: BinaryEncoders.encodeMonitoredItemModifyResult(writer, obj); break;
            case 761: BinaryEncoders.encodeModifyMonitoredItemsRequest(writer, obj); break;
            case 764: BinaryEncoders.encodeModifyMonitoredItemsResponse(writer, obj); break;
            case 767: BinaryEncoders.encodeSetMonitoringModeRequest(writer, obj); break;
            case 770: BinaryEncoders.encodeSetMonitoringModeResponse(writer, obj); break;
            case 773: BinaryEncoders.encodeSetTriggeringRequest(writer, obj); break;
            case 776: BinaryEncoders.encodeSetTriggeringResponse(writer, obj); break;
            case 779: BinaryEncoders.encodeDeleteMonitoredItemsRequest(writer, obj); break;
            case 782: BinaryEncoders.encodeDeleteMonitoredItemsResponse(writer, obj); break;
            case 785: BinaryEncoders.encodeCreateSubscriptionRequest(writer, obj); break;
            case 788: BinaryEncoders.encodeCreateSubscriptionResponse(writer, obj); break;
            case 791: BinaryEncoders.encodeModifySubscriptionRequest(writer, obj); break;
            case 794: BinaryEncoders.encodeModifySubscriptionResponse(writer, obj); break;
            case 797: BinaryEncoders.encodeSetPublishingModeRequest(writer, obj); break;
            case 800: BinaryEncoders.encodeSetPublishingModeResponse(writer, obj); break;
            case 803: BinaryEncoders.encodeNotificationMessage(writer, obj); break;
            case 806: BinaryEncoders.encodeMonitoredItemNotification(writer, obj); break;
            case 809: BinaryEncoders.encodeDataChangeNotification(writer, obj); break;
            case 818: BinaryEncoders.encodeStatusChangeNotification(writer, obj); break;
            case 821: BinaryEncoders.encodeSubscriptionAcknowledgement(writer, obj); break;
            case 824: BinaryEncoders.encodePublishRequest(writer, obj); break;
            case 827: BinaryEncoders.encodePublishResponse(writer, obj); break;
            case 830: BinaryEncoders.encodeRepublishRequest(writer, obj); break;
            case 833: BinaryEncoders.encodeRepublishResponse(writer, obj); break;
            case 836: BinaryEncoders.encodeTransferResult(writer, obj); break;
            case 839: BinaryEncoders.encodeTransferSubscriptionsRequest(writer, obj); break;
            case 842: BinaryEncoders.encodeTransferSubscriptionsResponse(writer, obj); break;
            case 845: BinaryEncoders.encodeDeleteSubscriptionsRequest(writer, obj); break;
            case 848: BinaryEncoders.encodeDeleteSubscriptionsResponse(writer, obj); break;
            case 853: BinaryEncoders.encodeRedundantServerDataType(writer, obj); break;
            case 856: BinaryEncoders.encodeSamplingIntervalDiagnosticsDataType(writer, obj); break;
            case 859: BinaryEncoders.encodeServerDiagnosticsSummaryDataType(writer, obj); break;
            case 862: BinaryEncoders.encodeServerStatusDataType(writer, obj); break;
            case 865: BinaryEncoders.encodeSessionDiagnosticsDataType(writer, obj); break;
            case 868: BinaryEncoders.encodeSessionSecurityDiagnosticsDataType(writer, obj); break;
            case 871: BinaryEncoders.encodeServiceCounterDataType(writer, obj); break;
            case 874: BinaryEncoders.encodeSubscriptionDiagnosticsDataType(writer, obj); break;
            case 877: BinaryEncoders.encodeModelChangeStructureDataType(writer, obj); break;
            case 884: BinaryEncoders.encodeRange(writer, obj); break;
            case 887: BinaryEncoders.encodeEUInformation(writer, obj); break;
            case 891: BinaryEncoders.encodeAnnotation(writer, obj); break;
            case 894: BinaryEncoders.encodeProgramDiagnosticDataType(writer, obj); break;
            case 897: BinaryEncoders.encodeSemanticChangeStructureDataType(writer, obj); break;
            case 914: BinaryEncoders.encodeEventNotificationList(writer, obj); break;
            case 917: BinaryEncoders.encodeEventFieldList(writer, obj); break;
            case 920: BinaryEncoders.encodeHistoryEventFieldList(writer, obj); break;
            case 938: BinaryEncoders.encodeIssuedIdentityToken(writer, obj); break;
            case 948: BinaryEncoders.encodeAggregateConfiguration(writer, obj); break;
            case 7594: BinaryEncoders.encodeEnumValueType(writer, obj); break;
            case 8912: BinaryEncoders.encodeTimeZoneDataType(writer, obj); break;
            case 11216: BinaryEncoders.encodeModificationInfo(writer, obj); break;
            case 11217: BinaryEncoders.encodeHistoryModifiedData(writer, obj); break;
            case 11295: BinaryEncoders.encodeUpdateStructureDataDetails(writer, obj); break;
            case 11943: BinaryEncoders.encodeEndpointUrlListDataType(writer, obj); break;
            case 11944: BinaryEncoders.encodeNetworkGroupDataType(writer, obj); break;
            case 12079: BinaryEncoders.encodeAxisInformation(writer, obj); break;
            case 12080: BinaryEncoders.encodeXVType(writer, obj); break;
            case 12171: BinaryEncoders.encodeComplexNumberType(writer, obj); break;
            case 12172: BinaryEncoders.encodeDoubleComplexNumberType(writer, obj); break;
            case 12189: BinaryEncoders.encodeServerOnNetwork(writer, obj); break;
            case 12190: BinaryEncoders.encodeFindServersOnNetworkRequest(writer, obj); break;
            case 12191: BinaryEncoders.encodeFindServersOnNetworkResponse(writer, obj); break;
            case 12193: BinaryEncoders.encodeRegisterServer2Request(writer, obj); break;
            case 12194: BinaryEncoders.encodeRegisterServer2Response(writer, obj); break;
            case 12554: BinaryEncoders.encodeTrustListDataType(writer, obj); break;
            case 12755: BinaryEncoders.encodeOptionSet(writer, obj); break;
            case 12756: BinaryEncoders.encodeUnion(writer, obj); break;
            case 12891: BinaryEncoders.encodeMdnsDiscoveryConfiguration(writer, obj); break;
            case 14273: BinaryEncoders.encodePublishedVariableDataType(writer, obj); break;
            case 14523: BinaryEncoders.encodeDataSetMetaDataType(writer, obj); break;
            case 14524: BinaryEncoders.encodeFieldMetaData(writer, obj); break;
            case 14525: BinaryEncoders.encodeDataTypeDescription(writer, obj); break;
            case 14533: BinaryEncoders.encodeKeyValuePair(writer, obj); break;
            case 14593: BinaryEncoders.encodeConfigurationVersionDataType(writer, obj); break;
            case 14744: BinaryEncoders.encodeFieldTargetDataType(writer, obj); break;
            case 15005: BinaryEncoders.encodeSimpleTypeDescription(writer, obj); break;
            case 15006: BinaryEncoders.encodeUABinaryFileDataType(writer, obj); break;
            case 15007: BinaryEncoders.encodeBrokerConnectionTransportDataType(writer, obj); break;
            case 15434: BinaryEncoders.encodeBaseConfigurationDataType(writer, obj); break;
            case 15435: BinaryEncoders.encodeBaseConfigurationRecordDataType(writer, obj); break;
            case 15436: BinaryEncoders.encodeCertificateGroupDataType(writer, obj); break;
            case 15480: BinaryEncoders.encodeWriterGroupDataType(writer, obj); break;
            case 15487: BinaryEncoders.encodeStructureDescription(writer, obj); break;
            case 15488: BinaryEncoders.encodeEnumDescription(writer, obj); break;
            case 15502: BinaryEncoders.encodeNetworkAddressDataType(writer, obj); break;
            case 15510: BinaryEncoders.encodeNetworkAddressUrlDataType(writer, obj); break;
            case 15520: BinaryEncoders.encodeReaderGroupDataType(writer, obj); break;
            case 15528: BinaryEncoders.encodeEndpointType(writer, obj); break;
            case 15530: BinaryEncoders.encodePubSubConfigurationDataType(writer, obj); break;
            case 15532: BinaryEncoders.encodeDatagramWriterGroupTransportDataType(writer, obj); break;
            case 15534: BinaryEncoders.encodeDataTypeSchemaHeader(writer, obj); break;
            case 15538: BinaryEncoders.encodeConfigurationUpdateTargetType(writer, obj); break;
            case 15556: BinaryEncoders.encodeApplicationIdentityDataType(writer, obj); break;
            case 15557: BinaryEncoders.encodeEndpointDataType(writer, obj); break;
            case 15558: BinaryEncoders.encodeServerEndpointDataType(writer, obj); break;
            case 15559: BinaryEncoders.encodeSecuritySettingsDataType(writer, obj); break;
            case 15560: BinaryEncoders.encodeUserTokenSettingsDataType(writer, obj); break;
            case 15578: BinaryEncoders.encodePublishedDataSetDataType(writer, obj); break;
            case 15580: BinaryEncoders.encodePublishedDataSetSourceDataType(writer, obj); break;
            case 15581: BinaryEncoders.encodePublishedDataItemsDataType(writer, obj); break;
            case 15582: BinaryEncoders.encodePublishedEventsDataType(writer, obj); break;
            case 15597: BinaryEncoders.encodeDataSetWriterDataType(writer, obj); break;
            case 15598: BinaryEncoders.encodeDataSetWriterTransportDataType(writer, obj); break;
            case 15605: BinaryEncoders.encodeDataSetWriterMessageDataType(writer, obj); break;
            case 15609: BinaryEncoders.encodePubSubGroupDataType(writer, obj); break;
            case 15611: BinaryEncoders.encodeWriterGroupTransportDataType(writer, obj); break;
            case 15616: BinaryEncoders.encodeWriterGroupMessageDataType(writer, obj); break;
            case 15617: BinaryEncoders.encodePubSubConnectionDataType(writer, obj); break;
            case 15618: BinaryEncoders.encodeConnectionTransportDataType(writer, obj); break;
            case 15621: BinaryEncoders.encodeReaderGroupTransportDataType(writer, obj); break;
            case 15622: BinaryEncoders.encodeReaderGroupMessageDataType(writer, obj); break;
            case 15623: BinaryEncoders.encodeDataSetReaderDataType(writer, obj); break;
            case 15628: BinaryEncoders.encodeDataSetReaderTransportDataType(writer, obj); break;
            case 15629: BinaryEncoders.encodeDataSetReaderMessageDataType(writer, obj); break;
            case 15630: BinaryEncoders.encodeSubscribedDataSetDataType(writer, obj); break;
            case 15631: BinaryEncoders.encodeTargetVariablesDataType(writer, obj); break;
            case 15634: BinaryEncoders.encodeIdentityMappingRuleType(writer, obj); break;
            case 15635: BinaryEncoders.encodeSubscribedDataSetMirrorDataType(writer, obj); break;
            case 15645: BinaryEncoders.encodeUadpWriterGroupMessageDataType(writer, obj); break;
            case 15652: BinaryEncoders.encodeUadpDataSetWriterMessageDataType(writer, obj); break;
            case 15653: BinaryEncoders.encodeUadpDataSetReaderMessageDataType(writer, obj); break;
            case 15657: BinaryEncoders.encodeJsonWriterGroupMessageDataType(writer, obj); break;
            case 15664: BinaryEncoders.encodeJsonDataSetWriterMessageDataType(writer, obj); break;
            case 15665: BinaryEncoders.encodeJsonDataSetReaderMessageDataType(writer, obj); break;
            case 15667: BinaryEncoders.encodeBrokerWriterGroupTransportDataType(writer, obj); break;
            case 15669: BinaryEncoders.encodeBrokerDataSetWriterTransportDataType(writer, obj); break;
            case 15670: BinaryEncoders.encodeBrokerDataSetReaderTransportDataType(writer, obj); break;
            case 15901: BinaryEncoders.encodeSessionlessInvokeRequestType(writer, obj); break;
            case 16313: BinaryEncoders.encodeAdditionalParametersType(writer, obj); break;
            case 17467: BinaryEncoders.encodeDatagramConnectionTransportDataType(writer, obj); break;
            case 17548: BinaryEncoders.encodeEphemeralKeyType(writer, obj); break;
            case 17606: BinaryEncoders.encodeGenericAttributeValue(writer, obj); break;
            case 17607: BinaryEncoders.encodeGenericAttributes(writer, obj); break;
            case 17861: BinaryEncoders.encodeDecimalDataType(writer, obj); break;
            case 18593: BinaryEncoders.encodeActionTargetDataType(writer, obj); break;
            case 18594: BinaryEncoders.encodePublishedActionDataType(writer, obj); break;
            case 18597: BinaryEncoders.encodeActionMethodDataType(writer, obj); break;
            case 18648: BinaryEncoders.encodeSortRuleElement(writer, obj); break;
            case 18649: BinaryEncoders.encodeReadEventDetailsSorted(writer, obj); break;
            case 18793: BinaryEncoders.encodePublishedActionMethodDataType(writer, obj); break;
            case 18794: BinaryEncoders.encodeDtlsPubSubConnectionDataType(writer, obj); break;
            case 18806: BinaryEncoders.encodeRationalNumber(writer, obj); break;
            case 18807: BinaryEncoders.encodeVector(writer, obj); break;
            case 18808: BinaryEncoders.encodeThreeDVector(writer, obj); break;
            case 18809: BinaryEncoders.encodeCartesianCoordinates(writer, obj); break;
            case 18810: BinaryEncoders.encodeThreeDCartesianCoordinates(writer, obj); break;
            case 18811: BinaryEncoders.encodeOrientation(writer, obj); break;
            case 18812: BinaryEncoders.encodeThreeDOrientation(writer, obj); break;
            case 18813: BinaryEncoders.encodeFrame(writer, obj); break;
            case 18814: BinaryEncoders.encodeThreeDFrame(writer, obj); break;
            case 18953: BinaryEncoders.encodeLldpManagementAddressTxPortType(writer, obj); break;
            case 18954: BinaryEncoders.encodeLldpManagementAddressType(writer, obj); break;
            case 18955: BinaryEncoders.encodeLldpTlvType(writer, obj); break;
            case 19311: BinaryEncoders.encodeJsonNetworkMessage(writer, obj); break;
            case 19312: BinaryEncoders.encodeJsonDataSetMessage(writer, obj); break;
            case 19313: BinaryEncoders.encodeJsonDataSetMetaDataMessage(writer, obj); break;
            case 19314: BinaryEncoders.encodeJsonApplicationDescriptionMessage(writer, obj); break;
            case 19315: BinaryEncoders.encodeJsonServerEndpointsMessage(writer, obj); break;
            case 19316: BinaryEncoders.encodeJsonStatusMessage(writer, obj); break;
            case 19317: BinaryEncoders.encodeJsonPubSubConnectionMessage(writer, obj); break;
            case 19318: BinaryEncoders.encodeJsonActionMetaDataMessage(writer, obj); break;
            case 19319: BinaryEncoders.encodeJsonActionResponderMessage(writer, obj); break;
            case 19320: BinaryEncoders.encodeJsonActionNetworkMessage(writer, obj); break;
            case 19321: BinaryEncoders.encodeJsonActionRequestMessage(writer, obj); break;
            case 19322: BinaryEncoders.encodeJsonActionResponseMessage(writer, obj); break;
            case 19361: BinaryEncoders.encodeLogRecord(writer, obj); break;
            case 19745: BinaryEncoders.encodeLogRecordsDataType(writer, obj); break;
            case 19746: BinaryEncoders.encodeSpanContextDataType(writer, obj); break;
            case 19747: BinaryEncoders.encodeTraceContextDataType(writer, obj); break;
            case 19748: BinaryEncoders.encodeNameValuePair(writer, obj); break;
            case 20999: BinaryEncoders.encodeSessionlessInvokeResponseType(writer, obj); break;
            case 23468: BinaryEncoders.encodeAliasNameDataType(writer, obj); break;
            case 23497: BinaryEncoders.encodeReadAnnotationDataDetails(writer, obj); break;
            case 23498: BinaryEncoders.encodeCurrencyUnitType(writer, obj); break;
            case 23599: BinaryEncoders.encodeStandaloneSubscribedDataSetRefDataType(writer, obj); break;
            case 23600: BinaryEncoders.encodeStandaloneSubscribedDataSetDataType(writer, obj); break;
            case 23601: BinaryEncoders.encodeSecurityGroupDataType(writer, obj); break;
            case 23602: BinaryEncoders.encodePubSubConfiguration2DataType(writer, obj); break;
            case 23603: BinaryEncoders.encodeQosDataType(writer, obj); break;
            case 23604: BinaryEncoders.encodeTransmitQosDataType(writer, obj); break;
            case 23605: BinaryEncoders.encodeTransmitQosPriorityDataType(writer, obj); break;
            case 23608: BinaryEncoders.encodeReceiveQosDataType(writer, obj); break;
            case 23609: BinaryEncoders.encodeReceiveQosPriorityDataType(writer, obj); break;
            case 23612: BinaryEncoders.encodeDatagramConnectionTransport2DataType(writer, obj); break;
            case 23613: BinaryEncoders.encodeDatagramWriterGroupTransport2DataType(writer, obj); break;
            case 23614: BinaryEncoders.encodeDatagramDataSetReaderTransportDataType(writer, obj); break;
            case 23724: BinaryEncoders.encodeServiceCertificateDataType(writer, obj); break;
            case 23743: BinaryEncoders.encodeApplicationConfigurationDataType(writer, obj); break;
            case 23744: BinaryEncoders.encodeAuthorizationServiceConfigurationDataType(writer, obj); break;
            case 24033: BinaryEncoders.encodeProgramDiagnostic2DataType(writer, obj); break;
            case 24105: BinaryEncoders.encodePortableQualifiedName(writer, obj); break;
            case 24106: BinaryEncoders.encodePortableNodeId(writer, obj); break;
            case 24107: BinaryEncoders.encodeUnsignedRationalNumber(writer, obj); break;
            case 24281: BinaryEncoders.encodeUserManagementDataType(writer, obj); break;
            case 25220: BinaryEncoders.encodePriorityMappingEntryType(writer, obj); break;
            case 25269: BinaryEncoders.encodePublishedDataSetCustomSourceDataType(writer, obj); break;
            case 25270: BinaryEncoders.encodePubSubKeyPushTargetDataType(writer, obj); break;
            case 25519: BinaryEncoders.encodePubSubConfigurationRefDataType(writer, obj); break;
            case 25520: BinaryEncoders.encodePubSubConfigurationValueDataType(writer, obj); break;
            case 32285: BinaryEncoders.encodeTransactionErrorType(writer, obj); break;
            case 32421: BinaryEncoders.encodeBitFieldDefinition(writer, obj); break;
            case 32434: BinaryEncoders.encodeAnnotationDataType(writer, obj); break;
            case 32435: BinaryEncoders.encodeLinearConversionDataType(writer, obj); break;
            case 32438: BinaryEncoders.encodeQuantityDimension(writer, obj); break;
            case 32659: BinaryEncoders.encodeReferenceDescriptionDataType(writer, obj); break;
            case 32660: BinaryEncoders.encodeReferenceListEntryDataType(writer, obj); break;
            case 32799: BinaryEncoders.encodeReadEventDetails2(writer, obj); break;
            case 32824: BinaryEncoders.encodeHistoryModifiedEvent(writer, obj); break;
            default:
                throw new Error(`Binary encoder for id ${id} not found`);
        }
    }

    public static decode(reader: BufferReader): unknown {
        const eid = reader.readExpandedNodeId();
        const id = eid.NodeId.Identifier as number;
        switch (id) {
            case 121: return BinaryDecoders.decodeDataTypeDefinition(reader);
            case 122: return BinaryDecoders.decodeStructureDefinition(reader);
            case 123: return BinaryDecoders.decodeEnumDefinition(reader);
            case 124: return BinaryDecoders.decodeDataSetMetaDataType(reader);
            case 125: return BinaryDecoders.decodeDataTypeDescription(reader);
            case 126: return BinaryDecoders.decodeStructureDescription(reader);
            case 127: return BinaryDecoders.decodeEnumDescription(reader);
            case 128: return BinaryDecoders.decodeRolePermissionType(reader);
            case 260: return BinaryDecoders.decodeNode(reader);
            case 263: return BinaryDecoders.decodeObjectNode(reader);
            case 266: return BinaryDecoders.decodeObjectTypeNode(reader);
            case 269: return BinaryDecoders.decodeVariableNode(reader);
            case 272: return BinaryDecoders.decodeVariableTypeNode(reader);
            case 275: return BinaryDecoders.decodeReferenceTypeNode(reader);
            case 278: return BinaryDecoders.decodeMethodNode(reader);
            case 281: return BinaryDecoders.decodeViewNode(reader);
            case 284: return BinaryDecoders.decodeDataTypeNode(reader);
            case 287: return BinaryDecoders.decodeReferenceNode(reader);
            case 298: return BinaryDecoders.decodeArgument(reader);
            case 301: return BinaryDecoders.decodeStatusResult(reader);
            case 306: return BinaryDecoders.decodeUserTokenPolicy(reader);
            case 310: return BinaryDecoders.decodeApplicationDescription(reader);
            case 314: return BinaryDecoders.decodeEndpointDescription(reader);
            case 318: return BinaryDecoders.decodeUserIdentityToken(reader);
            case 324: return BinaryDecoders.decodeUserNameIdentityToken(reader);
            case 327: return BinaryDecoders.decodeX509IdentityToken(reader);
            case 333: return BinaryDecoders.decodeEndpointConfiguration(reader);
            case 340: return BinaryDecoders.decodeBuildInfo(reader);
            case 346: return BinaryDecoders.decodeSignedSoftwareCertificate(reader);
            case 351: return BinaryDecoders.decodeNodeAttributes(reader);
            case 354: return BinaryDecoders.decodeObjectAttributes(reader);
            case 357: return BinaryDecoders.decodeVariableAttributes(reader);
            case 360: return BinaryDecoders.decodeMethodAttributes(reader);
            case 363: return BinaryDecoders.decodeObjectTypeAttributes(reader);
            case 366: return BinaryDecoders.decodeVariableTypeAttributes(reader);
            case 369: return BinaryDecoders.decodeReferenceTypeAttributes(reader);
            case 372: return BinaryDecoders.decodeDataTypeAttributes(reader);
            case 375: return BinaryDecoders.decodeViewAttributes(reader);
            case 378: return BinaryDecoders.decodeAddNodesItem(reader);
            case 381: return BinaryDecoders.decodeAddReferencesItem(reader);
            case 384: return BinaryDecoders.decodeDeleteNodesItem(reader);
            case 387: return BinaryDecoders.decodeDeleteReferencesItem(reader);
            case 391: return BinaryDecoders.decodeRequestHeader(reader);
            case 394: return BinaryDecoders.decodeResponseHeader(reader);
            case 397: return BinaryDecoders.decodeServiceFault(reader);
            case 422: return BinaryDecoders.decodeFindServersRequest(reader);
            case 425: return BinaryDecoders.decodeFindServersResponse(reader);
            case 428: return BinaryDecoders.decodeGetEndpointsRequest(reader);
            case 431: return BinaryDecoders.decodeGetEndpointsResponse(reader);
            case 434: return BinaryDecoders.decodeRegisteredServer(reader);
            case 437: return BinaryDecoders.decodeRegisterServerRequest(reader);
            case 440: return BinaryDecoders.decodeRegisterServerResponse(reader);
            case 443: return BinaryDecoders.decodeChannelSecurityToken(reader);
            case 446: return BinaryDecoders.decodeOpenSecureChannelRequest(reader);
            case 449: return BinaryDecoders.decodeOpenSecureChannelResponse(reader);
            case 452: return BinaryDecoders.decodeCloseSecureChannelRequest(reader);
            case 455: return BinaryDecoders.decodeCloseSecureChannelResponse(reader);
            case 458: return BinaryDecoders.decodeSignatureData(reader);
            case 461: return BinaryDecoders.decodeCreateSessionRequest(reader);
            case 464: return BinaryDecoders.decodeCreateSessionResponse(reader);
            case 467: return BinaryDecoders.decodeActivateSessionRequest(reader);
            case 470: return BinaryDecoders.decodeActivateSessionResponse(reader);
            case 473: return BinaryDecoders.decodeCloseSessionRequest(reader);
            case 476: return BinaryDecoders.decodeCloseSessionResponse(reader);
            case 479: return BinaryDecoders.decodeCancelRequest(reader);
            case 482: return BinaryDecoders.decodeCancelResponse(reader);
            case 485: return BinaryDecoders.decodeAddNodesResult(reader);
            case 488: return BinaryDecoders.decodeAddNodesRequest(reader);
            case 491: return BinaryDecoders.decodeAddNodesResponse(reader);
            case 494: return BinaryDecoders.decodeAddReferencesRequest(reader);
            case 497: return BinaryDecoders.decodeAddReferencesResponse(reader);
            case 500: return BinaryDecoders.decodeDeleteNodesRequest(reader);
            case 503: return BinaryDecoders.decodeDeleteNodesResponse(reader);
            case 506: return BinaryDecoders.decodeDeleteReferencesRequest(reader);
            case 509: return BinaryDecoders.decodeDeleteReferencesResponse(reader);
            case 513: return BinaryDecoders.decodeViewDescription(reader);
            case 516: return BinaryDecoders.decodeBrowseDescription(reader);
            case 520: return BinaryDecoders.decodeReferenceDescription(reader);
            case 524: return BinaryDecoders.decodeBrowseResult(reader);
            case 527: return BinaryDecoders.decodeBrowseRequest(reader);
            case 530: return BinaryDecoders.decodeBrowseResponse(reader);
            case 533: return BinaryDecoders.decodeBrowseNextRequest(reader);
            case 536: return BinaryDecoders.decodeBrowseNextResponse(reader);
            case 539: return BinaryDecoders.decodeRelativePathElement(reader);
            case 542: return BinaryDecoders.decodeRelativePath(reader);
            case 545: return BinaryDecoders.decodeBrowsePath(reader);
            case 548: return BinaryDecoders.decodeBrowsePathTarget(reader);
            case 551: return BinaryDecoders.decodeBrowsePathResult(reader);
            case 554: return BinaryDecoders.decodeTranslateBrowsePathsToNodeIdsRequest(reader);
            case 557: return BinaryDecoders.decodeTranslateBrowsePathsToNodeIdsResponse(reader);
            case 560: return BinaryDecoders.decodeRegisterNodesRequest(reader);
            case 563: return BinaryDecoders.decodeRegisterNodesResponse(reader);
            case 566: return BinaryDecoders.decodeUnregisterNodesRequest(reader);
            case 569: return BinaryDecoders.decodeUnregisterNodesResponse(reader);
            case 572: return BinaryDecoders.decodeQueryDataDescription(reader);
            case 575: return BinaryDecoders.decodeNodeTypeDescription(reader);
            case 579: return BinaryDecoders.decodeQueryDataSet(reader);
            case 582: return BinaryDecoders.decodeNodeReference(reader);
            case 585: return BinaryDecoders.decodeContentFilterElement(reader);
            case 588: return BinaryDecoders.decodeContentFilter(reader);
            case 591: return BinaryDecoders.decodeFilterOperand(reader);
            case 594: return BinaryDecoders.decodeElementOperand(reader);
            case 597: return BinaryDecoders.decodeLiteralOperand(reader);
            case 600: return BinaryDecoders.decodeAttributeOperand(reader);
            case 603: return BinaryDecoders.decodeSimpleAttributeOperand(reader);
            case 606: return BinaryDecoders.decodeContentFilterElementResult(reader);
            case 609: return BinaryDecoders.decodeContentFilterResult(reader);
            case 612: return BinaryDecoders.decodeParsingResult(reader);
            case 615: return BinaryDecoders.decodeQueryFirstRequest(reader);
            case 618: return BinaryDecoders.decodeQueryFirstResponse(reader);
            case 621: return BinaryDecoders.decodeQueryNextRequest(reader);
            case 624: return BinaryDecoders.decodeQueryNextResponse(reader);
            case 628: return BinaryDecoders.decodeReadValueId(reader);
            case 631: return BinaryDecoders.decodeReadRequest(reader);
            case 634: return BinaryDecoders.decodeReadResponse(reader);
            case 637: return BinaryDecoders.decodeHistoryReadValueId(reader);
            case 640: return BinaryDecoders.decodeHistoryReadResult(reader);
            case 643: return BinaryDecoders.decodeHistoryReadDetails(reader);
            case 646: return BinaryDecoders.decodeReadEventDetails(reader);
            case 649: return BinaryDecoders.decodeReadRawModifiedDetails(reader);
            case 652: return BinaryDecoders.decodeReadProcessedDetails(reader);
            case 655: return BinaryDecoders.decodeReadAtTimeDetails(reader);
            case 658: return BinaryDecoders.decodeHistoryData(reader);
            case 661: return BinaryDecoders.decodeHistoryEvent(reader);
            case 664: return BinaryDecoders.decodeHistoryReadRequest(reader);
            case 667: return BinaryDecoders.decodeHistoryReadResponse(reader);
            case 670: return BinaryDecoders.decodeWriteValue(reader);
            case 673: return BinaryDecoders.decodeWriteRequest(reader);
            case 676: return BinaryDecoders.decodeWriteResponse(reader);
            case 679: return BinaryDecoders.decodeHistoryUpdateDetails(reader);
            case 682: return BinaryDecoders.decodeUpdateDataDetails(reader);
            case 685: return BinaryDecoders.decodeUpdateEventDetails(reader);
            case 688: return BinaryDecoders.decodeDeleteRawModifiedDetails(reader);
            case 691: return BinaryDecoders.decodeDeleteAtTimeDetails(reader);
            case 694: return BinaryDecoders.decodeDeleteEventDetails(reader);
            case 697: return BinaryDecoders.decodeHistoryUpdateResult(reader);
            case 700: return BinaryDecoders.decodeHistoryUpdateRequest(reader);
            case 703: return BinaryDecoders.decodeHistoryUpdateResponse(reader);
            case 706: return BinaryDecoders.decodeCallMethodRequest(reader);
            case 709: return BinaryDecoders.decodeCallMethodResult(reader);
            case 712: return BinaryDecoders.decodeCallRequest(reader);
            case 715: return BinaryDecoders.decodeCallResponse(reader);
            case 724: return BinaryDecoders.decodeDataChangeFilter(reader);
            case 727: return BinaryDecoders.decodeEventFilter(reader);
            case 730: return BinaryDecoders.decodeAggregateFilter(reader);
            case 736: return BinaryDecoders.decodeEventFilterResult(reader);
            case 739: return BinaryDecoders.decodeAggregateFilterResult(reader);
            case 742: return BinaryDecoders.decodeMonitoringParameters(reader);
            case 745: return BinaryDecoders.decodeMonitoredItemCreateRequest(reader);
            case 748: return BinaryDecoders.decodeMonitoredItemCreateResult(reader);
            case 751: return BinaryDecoders.decodeCreateMonitoredItemsRequest(reader);
            case 754: return BinaryDecoders.decodeCreateMonitoredItemsResponse(reader);
            case 757: return BinaryDecoders.decodeMonitoredItemModifyRequest(reader);
            case 760: return BinaryDecoders.decodeMonitoredItemModifyResult(reader);
            case 763: return BinaryDecoders.decodeModifyMonitoredItemsRequest(reader);
            case 766: return BinaryDecoders.decodeModifyMonitoredItemsResponse(reader);
            case 769: return BinaryDecoders.decodeSetMonitoringModeRequest(reader);
            case 772: return BinaryDecoders.decodeSetMonitoringModeResponse(reader);
            case 775: return BinaryDecoders.decodeSetTriggeringRequest(reader);
            case 778: return BinaryDecoders.decodeSetTriggeringResponse(reader);
            case 781: return BinaryDecoders.decodeDeleteMonitoredItemsRequest(reader);
            case 784: return BinaryDecoders.decodeDeleteMonitoredItemsResponse(reader);
            case 787: return BinaryDecoders.decodeCreateSubscriptionRequest(reader);
            case 790: return BinaryDecoders.decodeCreateSubscriptionResponse(reader);
            case 793: return BinaryDecoders.decodeModifySubscriptionRequest(reader);
            case 796: return BinaryDecoders.decodeModifySubscriptionResponse(reader);
            case 799: return BinaryDecoders.decodeSetPublishingModeRequest(reader);
            case 802: return BinaryDecoders.decodeSetPublishingModeResponse(reader);
            case 805: return BinaryDecoders.decodeNotificationMessage(reader);
            case 808: return BinaryDecoders.decodeMonitoredItemNotification(reader);
            case 811: return BinaryDecoders.decodeDataChangeNotification(reader);
            case 820: return BinaryDecoders.decodeStatusChangeNotification(reader);
            case 823: return BinaryDecoders.decodeSubscriptionAcknowledgement(reader);
            case 826: return BinaryDecoders.decodePublishRequest(reader);
            case 829: return BinaryDecoders.decodePublishResponse(reader);
            case 832: return BinaryDecoders.decodeRepublishRequest(reader);
            case 835: return BinaryDecoders.decodeRepublishResponse(reader);
            case 838: return BinaryDecoders.decodeTransferResult(reader);
            case 841: return BinaryDecoders.decodeTransferSubscriptionsRequest(reader);
            case 844: return BinaryDecoders.decodeTransferSubscriptionsResponse(reader);
            case 847: return BinaryDecoders.decodeDeleteSubscriptionsRequest(reader);
            case 850: return BinaryDecoders.decodeDeleteSubscriptionsResponse(reader);
            case 855: return BinaryDecoders.decodeRedundantServerDataType(reader);
            case 858: return BinaryDecoders.decodeSamplingIntervalDiagnosticsDataType(reader);
            case 861: return BinaryDecoders.decodeServerDiagnosticsSummaryDataType(reader);
            case 864: return BinaryDecoders.decodeServerStatusDataType(reader);
            case 867: return BinaryDecoders.decodeSessionDiagnosticsDataType(reader);
            case 870: return BinaryDecoders.decodeSessionSecurityDiagnosticsDataType(reader);
            case 873: return BinaryDecoders.decodeServiceCounterDataType(reader);
            case 876: return BinaryDecoders.decodeSubscriptionDiagnosticsDataType(reader);
            case 879: return BinaryDecoders.decodeModelChangeStructureDataType(reader);
            case 886: return BinaryDecoders.decodeRange(reader);
            case 889: return BinaryDecoders.decodeEUInformation(reader);
            case 893: return BinaryDecoders.decodeAnnotation(reader);
            case 896: return BinaryDecoders.decodeProgramDiagnosticDataType(reader);
            case 899: return BinaryDecoders.decodeSemanticChangeStructureDataType(reader);
            case 916: return BinaryDecoders.decodeEventNotificationList(reader);
            case 919: return BinaryDecoders.decodeEventFieldList(reader);
            case 922: return BinaryDecoders.decodeHistoryEventFieldList(reader);
            case 940: return BinaryDecoders.decodeIssuedIdentityToken(reader);
            case 950: return BinaryDecoders.decodeAggregateConfiguration(reader);
            case 8251: return BinaryDecoders.decodeEnumValueType(reader);
            case 8917: return BinaryDecoders.decodeTimeZoneDataType(reader);
            case 11226: return BinaryDecoders.decodeModificationInfo(reader);
            case 11227: return BinaryDecoders.decodeHistoryModifiedData(reader);
            case 11300: return BinaryDecoders.decodeUpdateStructureDataDetails(reader);
            case 11957: return BinaryDecoders.decodeEndpointUrlListDataType(reader);
            case 11958: return BinaryDecoders.decodeNetworkGroupDataType(reader);
            case 12089: return BinaryDecoders.decodeAxisInformation(reader);
            case 12090: return BinaryDecoders.decodeXVType(reader);
            case 12181: return BinaryDecoders.decodeComplexNumberType(reader);
            case 12182: return BinaryDecoders.decodeDoubleComplexNumberType(reader);
            case 12207: return BinaryDecoders.decodeServerOnNetwork(reader);
            case 12208: return BinaryDecoders.decodeFindServersOnNetworkRequest(reader);
            case 12209: return BinaryDecoders.decodeFindServersOnNetworkResponse(reader);
            case 12211: return BinaryDecoders.decodeRegisterServer2Request(reader);
            case 12212: return BinaryDecoders.decodeRegisterServer2Response(reader);
            case 12680: return BinaryDecoders.decodeTrustListDataType(reader);
            case 12765: return BinaryDecoders.decodeOptionSet(reader);
            case 12766: return BinaryDecoders.decodeUnion(reader);
            case 12901: return BinaryDecoders.decodeMdnsDiscoveryConfiguration(reader);
            case 14323: return BinaryDecoders.decodePublishedVariableDataType(reader);
            case 14839: return BinaryDecoders.decodeFieldMetaData(reader);
            case 14844: return BinaryDecoders.decodeStructureField(reader);
            case 14845: return BinaryDecoders.decodeEnumField(reader);
            case 14846: return BinaryDecoders.decodeKeyValuePair(reader);
            case 14847: return BinaryDecoders.decodeConfigurationVersionDataType(reader);
            case 14848: return BinaryDecoders.decodeFieldTargetDataType(reader);
            case 15421: return BinaryDecoders.decodeSimpleTypeDescription(reader);
            case 15422: return BinaryDecoders.decodeUABinaryFileDataType(reader);
            case 15479: return BinaryDecoders.decodeBrokerConnectionTransportDataType(reader);
            case 15671: return BinaryDecoders.decodeEndpointType(reader);
            case 15676: return BinaryDecoders.decodeDataTypeSchemaHeader(reader);
            case 15677: return BinaryDecoders.decodePublishedDataSetDataType(reader);
            case 15678: return BinaryDecoders.decodePublishedDataSetSourceDataType(reader);
            case 15679: return BinaryDecoders.decodePublishedDataItemsDataType(reader);
            case 15681: return BinaryDecoders.decodePublishedEventsDataType(reader);
            case 15682: return BinaryDecoders.decodeDataSetWriterDataType(reader);
            case 15683: return BinaryDecoders.decodeDataSetWriterTransportDataType(reader);
            case 15688: return BinaryDecoders.decodeDataSetWriterMessageDataType(reader);
            case 15689: return BinaryDecoders.decodePubSubGroupDataType(reader);
            case 15691: return BinaryDecoders.decodeWriterGroupTransportDataType(reader);
            case 15693: return BinaryDecoders.decodeWriterGroupMessageDataType(reader);
            case 15694: return BinaryDecoders.decodePubSubConnectionDataType(reader);
            case 15695: return BinaryDecoders.decodeConnectionTransportDataType(reader);
            case 15701: return BinaryDecoders.decodeReaderGroupTransportDataType(reader);
            case 15702: return BinaryDecoders.decodeReaderGroupMessageDataType(reader);
            case 15703: return BinaryDecoders.decodeDataSetReaderDataType(reader);
            case 15705: return BinaryDecoders.decodeDataSetReaderTransportDataType(reader);
            case 15706: return BinaryDecoders.decodeDataSetReaderMessageDataType(reader);
            case 15707: return BinaryDecoders.decodeSubscribedDataSetDataType(reader);
            case 15712: return BinaryDecoders.decodeTargetVariablesDataType(reader);
            case 15713: return BinaryDecoders.decodeSubscribedDataSetMirrorDataType(reader);
            case 15715: return BinaryDecoders.decodeUadpWriterGroupMessageDataType(reader);
            case 15717: return BinaryDecoders.decodeUadpDataSetWriterMessageDataType(reader);
            case 15718: return BinaryDecoders.decodeUadpDataSetReaderMessageDataType(reader);
            case 15719: return BinaryDecoders.decodeJsonWriterGroupMessageDataType(reader);
            case 15724: return BinaryDecoders.decodeJsonDataSetWriterMessageDataType(reader);
            case 15725: return BinaryDecoders.decodeJsonDataSetReaderMessageDataType(reader);
            case 15727: return BinaryDecoders.decodeBrokerWriterGroupTransportDataType(reader);
            case 15729: return BinaryDecoders.decodeBrokerDataSetWriterTransportDataType(reader);
            case 15733: return BinaryDecoders.decodeBrokerDataSetReaderTransportDataType(reader);
            case 15736: return BinaryDecoders.decodeIdentityMappingRuleType(reader);
            case 15903: return BinaryDecoders.decodeSessionlessInvokeRequestType(reader);
            case 16538: return BinaryDecoders.decodeBaseConfigurationDataType(reader);
            case 16539: return BinaryDecoders.decodeBaseConfigurationRecordDataType(reader);
            case 16540: return BinaryDecoders.decodeCertificateGroupDataType(reader);
            case 16541: return BinaryDecoders.decodeConfigurationUpdateTargetType(reader);
            case 16543: return BinaryDecoders.decodeApplicationIdentityDataType(reader);
            case 16544: return BinaryDecoders.decodeEndpointDataType(reader);
            case 16545: return BinaryDecoders.decodeServerEndpointDataType(reader);
            case 16546: return BinaryDecoders.decodeSecuritySettingsDataType(reader);
            case 16547: return BinaryDecoders.decodeUserTokenSettingsDataType(reader);
            case 17468: return BinaryDecoders.decodeDatagramConnectionTransportDataType(reader);
            case 17537: return BinaryDecoders.decodeAdditionalParametersType(reader);
            case 17549: return BinaryDecoders.decodeEphemeralKeyType(reader);
            case 17610: return BinaryDecoders.decodeGenericAttributeValue(reader);
            case 17611: return BinaryDecoders.decodeGenericAttributes(reader);
            case 17863: return BinaryDecoders.decodeDecimalDataType(reader);
            case 18598: return BinaryDecoders.decodeActionTargetDataType(reader);
            case 18599: return BinaryDecoders.decodePublishedActionDataType(reader);
            case 18600: return BinaryDecoders.decodeActionMethodDataType(reader);
            case 18650: return BinaryDecoders.decodeSortRuleElement(reader);
            case 18651: return BinaryDecoders.decodeReadEventDetailsSorted(reader);
            case 18795: return BinaryDecoders.decodePublishedActionMethodDataType(reader);
            case 18815: return BinaryDecoders.decodeRationalNumber(reader);
            case 18816: return BinaryDecoders.decodeVector(reader);
            case 18817: return BinaryDecoders.decodeThreeDVector(reader);
            case 18818: return BinaryDecoders.decodeCartesianCoordinates(reader);
            case 18819: return BinaryDecoders.decodeThreeDCartesianCoordinates(reader);
            case 18820: return BinaryDecoders.decodeOrientation(reader);
            case 18821: return BinaryDecoders.decodeThreeDOrientation(reader);
            case 18822: return BinaryDecoders.decodeFrame(reader);
            case 18823: return BinaryDecoders.decodeThreeDFrame(reader);
            case 18930: return BinaryDecoders.decodeDtlsPubSubConnectionDataType(reader);
            case 19079: return BinaryDecoders.decodeLldpManagementAddressTxPortType(reader);
            case 19080: return BinaryDecoders.decodeLldpManagementAddressType(reader);
            case 19081: return BinaryDecoders.decodeLldpTlvType(reader);
            case 19379: return BinaryDecoders.decodeLogRecord(reader);
            case 19753: return BinaryDecoders.decodeLogRecordsDataType(reader);
            case 19754: return BinaryDecoders.decodeSpanContextDataType(reader);
            case 19755: return BinaryDecoders.decodeTraceContextDataType(reader);
            case 19756: return BinaryDecoders.decodeNameValuePair(reader);
            case 21001: return BinaryDecoders.decodeSessionlessInvokeResponseType(reader);
            case 21150: return BinaryDecoders.decodeWriterGroupDataType(reader);
            case 21151: return BinaryDecoders.decodeNetworkAddressDataType(reader);
            case 21152: return BinaryDecoders.decodeNetworkAddressUrlDataType(reader);
            case 21153: return BinaryDecoders.decodeReaderGroupDataType(reader);
            case 21154: return BinaryDecoders.decodePubSubConfigurationDataType(reader);
            case 21155: return BinaryDecoders.decodeDatagramWriterGroupTransportDataType(reader);
            case 23499: return BinaryDecoders.decodeAliasNameDataType(reader);
            case 23500: return BinaryDecoders.decodeReadAnnotationDataDetails(reader);
            case 23507: return BinaryDecoders.decodeCurrencyUnitType(reader);
            case 23725: return BinaryDecoders.decodeServiceCertificateDataType(reader);
            case 23754: return BinaryDecoders.decodeApplicationConfigurationDataType(reader);
            case 23755: return BinaryDecoders.decodeAuthorizationServiceConfigurationDataType(reader);
            case 23851: return BinaryDecoders.decodeStandaloneSubscribedDataSetRefDataType(reader);
            case 23852: return BinaryDecoders.decodeStandaloneSubscribedDataSetDataType(reader);
            case 23853: return BinaryDecoders.decodeSecurityGroupDataType(reader);
            case 23854: return BinaryDecoders.decodePubSubConfiguration2DataType(reader);
            case 23855: return BinaryDecoders.decodeQosDataType(reader);
            case 23856: return BinaryDecoders.decodeTransmitQosDataType(reader);
            case 23857: return BinaryDecoders.decodeTransmitQosPriorityDataType(reader);
            case 23860: return BinaryDecoders.decodeReceiveQosDataType(reader);
            case 23861: return BinaryDecoders.decodeReceiveQosPriorityDataType(reader);
            case 23864: return BinaryDecoders.decodeDatagramConnectionTransport2DataType(reader);
            case 23865: return BinaryDecoders.decodeDatagramWriterGroupTransport2DataType(reader);
            case 23866: return BinaryDecoders.decodeDatagramDataSetReaderTransportDataType(reader);
            case 24034: return BinaryDecoders.decodeProgramDiagnostic2DataType(reader);
            case 24108: return BinaryDecoders.decodePortableQualifiedName(reader);
            case 24109: return BinaryDecoders.decodePortableNodeId(reader);
            case 24110: return BinaryDecoders.decodeUnsignedRationalNumber(reader);
            case 24292: return BinaryDecoders.decodeUserManagementDataType(reader);
            case 25239: return BinaryDecoders.decodePriorityMappingEntryType(reader);
            case 25529: return BinaryDecoders.decodePublishedDataSetCustomSourceDataType(reader);
            case 25530: return BinaryDecoders.decodePubSubKeyPushTargetDataType(reader);
            case 25531: return BinaryDecoders.decodePubSubConfigurationRefDataType(reader);
            case 25532: return BinaryDecoders.decodePubSubConfigurationValueDataType(reader);
            case 32382: return BinaryDecoders.decodeTransactionErrorType(reader);
            case 32422: return BinaryDecoders.decodeBitFieldDefinition(reader);
            case 32560: return BinaryDecoders.decodeAnnotationDataType(reader);
            case 32561: return BinaryDecoders.decodeLinearConversionDataType(reader);
            case 32562: return BinaryDecoders.decodeQuantityDimension(reader);
            case 32661: return BinaryDecoders.decodeReferenceDescriptionDataType(reader);
            case 32662: return BinaryDecoders.decodeReferenceListEntryDataType(reader);
            case 32800: return BinaryDecoders.decodeReadEventDetails2(reader);
            case 32825: return BinaryDecoders.decodeHistoryModifiedEvent(reader);
            default:
                throw new Error(`Binary decoder for id ${id} not found`);
        }
    }
}
