// AUTO-GENERATED – DO NOT EDIT
import { BufferReader } from "../codecs/binary/bufferReader";
import { BufferWriter } from "../codecs/binary/bufferWriter";
import { IIdentifiable } from "../codecs/iIdentifiable";

export class SchemaCodec {

    public static encodeBinary(writer: BufferWriter, obj: IIdentifiable): void {
        const id = obj.id;
        switch (id) {
            case 29: require("./binaryEncoders").encodeEnumeration(writer, obj); break;
            case 96: require("./binaryEncoders").encodeRolePermissionType(writer, obj); break;
            case 97: require("./binaryEncoders").encodeDataTypeDefinition(writer, obj); break;
            case 99: require("./binaryEncoders").encodeStructureDefinition(writer, obj); break;
            case 100: require("./binaryEncoders").encodeEnumDefinition(writer, obj); break;
            case 101: require("./binaryEncoders").encodeStructureField(writer, obj); break;
            case 102: require("./binaryEncoders").encodeEnumField(writer, obj); break;
            case 258: require("./binaryEncoders").encodeNode(writer, obj); break;
            case 261: require("./binaryEncoders").encodeObjectNode(writer, obj); break;
            case 264: require("./binaryEncoders").encodeObjectTypeNode(writer, obj); break;
            case 267: require("./binaryEncoders").encodeVariableNode(writer, obj); break;
            case 270: require("./binaryEncoders").encodeVariableTypeNode(writer, obj); break;
            case 273: require("./binaryEncoders").encodeReferenceTypeNode(writer, obj); break;
            case 276: require("./binaryEncoders").encodeMethodNode(writer, obj); break;
            case 279: require("./binaryEncoders").encodeViewNode(writer, obj); break;
            case 282: require("./binaryEncoders").encodeDataTypeNode(writer, obj); break;
            case 285: require("./binaryEncoders").encodeReferenceNode(writer, obj); break;
            case 296: require("./binaryEncoders").encodeArgument(writer, obj); break;
            case 299: require("./binaryEncoders").encodeStatusResult(writer, obj); break;
            case 304: require("./binaryEncoders").encodeUserTokenPolicy(writer, obj); break;
            case 308: require("./binaryEncoders").encodeApplicationDescription(writer, obj); break;
            case 312: require("./binaryEncoders").encodeEndpointDescription(writer, obj); break;
            case 316: require("./binaryEncoders").encodeUserIdentityToken(writer, obj); break;
            case 322: require("./binaryEncoders").encodeUserNameIdentityToken(writer, obj); break;
            case 325: require("./binaryEncoders").encodeX509IdentityToken(writer, obj); break;
            case 331: require("./binaryEncoders").encodeEndpointConfiguration(writer, obj); break;
            case 338: require("./binaryEncoders").encodeBuildInfo(writer, obj); break;
            case 344: require("./binaryEncoders").encodeSignedSoftwareCertificate(writer, obj); break;
            case 349: require("./binaryEncoders").encodeNodeAttributes(writer, obj); break;
            case 352: require("./binaryEncoders").encodeObjectAttributes(writer, obj); break;
            case 355: require("./binaryEncoders").encodeVariableAttributes(writer, obj); break;
            case 358: require("./binaryEncoders").encodeMethodAttributes(writer, obj); break;
            case 361: require("./binaryEncoders").encodeObjectTypeAttributes(writer, obj); break;
            case 364: require("./binaryEncoders").encodeVariableTypeAttributes(writer, obj); break;
            case 367: require("./binaryEncoders").encodeReferenceTypeAttributes(writer, obj); break;
            case 370: require("./binaryEncoders").encodeDataTypeAttributes(writer, obj); break;
            case 373: require("./binaryEncoders").encodeViewAttributes(writer, obj); break;
            case 376: require("./binaryEncoders").encodeAddNodesItem(writer, obj); break;
            case 379: require("./binaryEncoders").encodeAddReferencesItem(writer, obj); break;
            case 382: require("./binaryEncoders").encodeDeleteNodesItem(writer, obj); break;
            case 385: require("./binaryEncoders").encodeDeleteReferencesItem(writer, obj); break;
            case 389: require("./binaryEncoders").encodeRequestHeader(writer, obj); break;
            case 392: require("./binaryEncoders").encodeResponseHeader(writer, obj); break;
            case 395: require("./binaryEncoders").encodeServiceFault(writer, obj); break;
            case 420: require("./binaryEncoders").encodeFindServersRequest(writer, obj); break;
            case 423: require("./binaryEncoders").encodeFindServersResponse(writer, obj); break;
            case 426: require("./binaryEncoders").encodeGetEndpointsRequest(writer, obj); break;
            case 429: require("./binaryEncoders").encodeGetEndpointsResponse(writer, obj); break;
            case 432: require("./binaryEncoders").encodeRegisteredServer(writer, obj); break;
            case 435: require("./binaryEncoders").encodeRegisterServerRequest(writer, obj); break;
            case 438: require("./binaryEncoders").encodeRegisterServerResponse(writer, obj); break;
            case 441: require("./binaryEncoders").encodeChannelSecurityToken(writer, obj); break;
            case 444: require("./binaryEncoders").encodeOpenSecureChannelRequest(writer, obj); break;
            case 447: require("./binaryEncoders").encodeOpenSecureChannelResponse(writer, obj); break;
            case 450: require("./binaryEncoders").encodeCloseSecureChannelRequest(writer, obj); break;
            case 453: require("./binaryEncoders").encodeCloseSecureChannelResponse(writer, obj); break;
            case 456: require("./binaryEncoders").encodeSignatureData(writer, obj); break;
            case 459: require("./binaryEncoders").encodeCreateSessionRequest(writer, obj); break;
            case 462: require("./binaryEncoders").encodeCreateSessionResponse(writer, obj); break;
            case 465: require("./binaryEncoders").encodeActivateSessionRequest(writer, obj); break;
            case 468: require("./binaryEncoders").encodeActivateSessionResponse(writer, obj); break;
            case 471: require("./binaryEncoders").encodeCloseSessionRequest(writer, obj); break;
            case 474: require("./binaryEncoders").encodeCloseSessionResponse(writer, obj); break;
            case 477: require("./binaryEncoders").encodeCancelRequest(writer, obj); break;
            case 480: require("./binaryEncoders").encodeCancelResponse(writer, obj); break;
            case 483: require("./binaryEncoders").encodeAddNodesResult(writer, obj); break;
            case 486: require("./binaryEncoders").encodeAddNodesRequest(writer, obj); break;
            case 489: require("./binaryEncoders").encodeAddNodesResponse(writer, obj); break;
            case 492: require("./binaryEncoders").encodeAddReferencesRequest(writer, obj); break;
            case 495: require("./binaryEncoders").encodeAddReferencesResponse(writer, obj); break;
            case 498: require("./binaryEncoders").encodeDeleteNodesRequest(writer, obj); break;
            case 501: require("./binaryEncoders").encodeDeleteNodesResponse(writer, obj); break;
            case 504: require("./binaryEncoders").encodeDeleteReferencesRequest(writer, obj); break;
            case 507: require("./binaryEncoders").encodeDeleteReferencesResponse(writer, obj); break;
            case 511: require("./binaryEncoders").encodeViewDescription(writer, obj); break;
            case 514: require("./binaryEncoders").encodeBrowseDescription(writer, obj); break;
            case 518: require("./binaryEncoders").encodeReferenceDescription(writer, obj); break;
            case 522: require("./binaryEncoders").encodeBrowseResult(writer, obj); break;
            case 525: require("./binaryEncoders").encodeBrowseRequest(writer, obj); break;
            case 528: require("./binaryEncoders").encodeBrowseResponse(writer, obj); break;
            case 531: require("./binaryEncoders").encodeBrowseNextRequest(writer, obj); break;
            case 534: require("./binaryEncoders").encodeBrowseNextResponse(writer, obj); break;
            case 537: require("./binaryEncoders").encodeRelativePathElement(writer, obj); break;
            case 540: require("./binaryEncoders").encodeRelativePath(writer, obj); break;
            case 543: require("./binaryEncoders").encodeBrowsePath(writer, obj); break;
            case 546: require("./binaryEncoders").encodeBrowsePathTarget(writer, obj); break;
            case 549: require("./binaryEncoders").encodeBrowsePathResult(writer, obj); break;
            case 552: require("./binaryEncoders").encodeTranslateBrowsePathsToNodeIdsRequest(writer, obj); break;
            case 555: require("./binaryEncoders").encodeTranslateBrowsePathsToNodeIdsResponse(writer, obj); break;
            case 558: require("./binaryEncoders").encodeRegisterNodesRequest(writer, obj); break;
            case 561: require("./binaryEncoders").encodeRegisterNodesResponse(writer, obj); break;
            case 564: require("./binaryEncoders").encodeUnregisterNodesRequest(writer, obj); break;
            case 567: require("./binaryEncoders").encodeUnregisterNodesResponse(writer, obj); break;
            case 570: require("./binaryEncoders").encodeQueryDataDescription(writer, obj); break;
            case 573: require("./binaryEncoders").encodeNodeTypeDescription(writer, obj); break;
            case 577: require("./binaryEncoders").encodeQueryDataSet(writer, obj); break;
            case 580: require("./binaryEncoders").encodeNodeReference(writer, obj); break;
            case 583: require("./binaryEncoders").encodeContentFilterElement(writer, obj); break;
            case 586: require("./binaryEncoders").encodeContentFilter(writer, obj); break;
            case 589: require("./binaryEncoders").encodeFilterOperand(writer, obj); break;
            case 592: require("./binaryEncoders").encodeElementOperand(writer, obj); break;
            case 595: require("./binaryEncoders").encodeLiteralOperand(writer, obj); break;
            case 598: require("./binaryEncoders").encodeAttributeOperand(writer, obj); break;
            case 601: require("./binaryEncoders").encodeSimpleAttributeOperand(writer, obj); break;
            case 604: require("./binaryEncoders").encodeContentFilterElementResult(writer, obj); break;
            case 607: require("./binaryEncoders").encodeContentFilterResult(writer, obj); break;
            case 610: require("./binaryEncoders").encodeParsingResult(writer, obj); break;
            case 613: require("./binaryEncoders").encodeQueryFirstRequest(writer, obj); break;
            case 616: require("./binaryEncoders").encodeQueryFirstResponse(writer, obj); break;
            case 619: require("./binaryEncoders").encodeQueryNextRequest(writer, obj); break;
            case 622: require("./binaryEncoders").encodeQueryNextResponse(writer, obj); break;
            case 626: require("./binaryEncoders").encodeReadValueId(writer, obj); break;
            case 629: require("./binaryEncoders").encodeReadRequest(writer, obj); break;
            case 632: require("./binaryEncoders").encodeReadResponse(writer, obj); break;
            case 635: require("./binaryEncoders").encodeHistoryReadValueId(writer, obj); break;
            case 638: require("./binaryEncoders").encodeHistoryReadResult(writer, obj); break;
            case 641: require("./binaryEncoders").encodeHistoryReadDetails(writer, obj); break;
            case 644: require("./binaryEncoders").encodeReadEventDetails(writer, obj); break;
            case 647: require("./binaryEncoders").encodeReadRawModifiedDetails(writer, obj); break;
            case 650: require("./binaryEncoders").encodeReadProcessedDetails(writer, obj); break;
            case 653: require("./binaryEncoders").encodeReadAtTimeDetails(writer, obj); break;
            case 656: require("./binaryEncoders").encodeHistoryData(writer, obj); break;
            case 659: require("./binaryEncoders").encodeHistoryEvent(writer, obj); break;
            case 662: require("./binaryEncoders").encodeHistoryReadRequest(writer, obj); break;
            case 665: require("./binaryEncoders").encodeHistoryReadResponse(writer, obj); break;
            case 668: require("./binaryEncoders").encodeWriteValue(writer, obj); break;
            case 671: require("./binaryEncoders").encodeWriteRequest(writer, obj); break;
            case 674: require("./binaryEncoders").encodeWriteResponse(writer, obj); break;
            case 677: require("./binaryEncoders").encodeHistoryUpdateDetails(writer, obj); break;
            case 680: require("./binaryEncoders").encodeUpdateDataDetails(writer, obj); break;
            case 683: require("./binaryEncoders").encodeUpdateEventDetails(writer, obj); break;
            case 686: require("./binaryEncoders").encodeDeleteRawModifiedDetails(writer, obj); break;
            case 689: require("./binaryEncoders").encodeDeleteAtTimeDetails(writer, obj); break;
            case 692: require("./binaryEncoders").encodeDeleteEventDetails(writer, obj); break;
            case 695: require("./binaryEncoders").encodeHistoryUpdateResult(writer, obj); break;
            case 698: require("./binaryEncoders").encodeHistoryUpdateRequest(writer, obj); break;
            case 701: require("./binaryEncoders").encodeHistoryUpdateResponse(writer, obj); break;
            case 704: require("./binaryEncoders").encodeCallMethodRequest(writer, obj); break;
            case 707: require("./binaryEncoders").encodeCallMethodResult(writer, obj); break;
            case 710: require("./binaryEncoders").encodeCallRequest(writer, obj); break;
            case 713: require("./binaryEncoders").encodeCallResponse(writer, obj); break;
            case 722: require("./binaryEncoders").encodeDataChangeFilter(writer, obj); break;
            case 725: require("./binaryEncoders").encodeEventFilter(writer, obj); break;
            case 728: require("./binaryEncoders").encodeAggregateFilter(writer, obj); break;
            case 734: require("./binaryEncoders").encodeEventFilterResult(writer, obj); break;
            case 737: require("./binaryEncoders").encodeAggregateFilterResult(writer, obj); break;
            case 740: require("./binaryEncoders").encodeMonitoringParameters(writer, obj); break;
            case 743: require("./binaryEncoders").encodeMonitoredItemCreateRequest(writer, obj); break;
            case 746: require("./binaryEncoders").encodeMonitoredItemCreateResult(writer, obj); break;
            case 749: require("./binaryEncoders").encodeCreateMonitoredItemsRequest(writer, obj); break;
            case 752: require("./binaryEncoders").encodeCreateMonitoredItemsResponse(writer, obj); break;
            case 755: require("./binaryEncoders").encodeMonitoredItemModifyRequest(writer, obj); break;
            case 758: require("./binaryEncoders").encodeMonitoredItemModifyResult(writer, obj); break;
            case 761: require("./binaryEncoders").encodeModifyMonitoredItemsRequest(writer, obj); break;
            case 764: require("./binaryEncoders").encodeModifyMonitoredItemsResponse(writer, obj); break;
            case 767: require("./binaryEncoders").encodeSetMonitoringModeRequest(writer, obj); break;
            case 770: require("./binaryEncoders").encodeSetMonitoringModeResponse(writer, obj); break;
            case 773: require("./binaryEncoders").encodeSetTriggeringRequest(writer, obj); break;
            case 776: require("./binaryEncoders").encodeSetTriggeringResponse(writer, obj); break;
            case 779: require("./binaryEncoders").encodeDeleteMonitoredItemsRequest(writer, obj); break;
            case 782: require("./binaryEncoders").encodeDeleteMonitoredItemsResponse(writer, obj); break;
            case 785: require("./binaryEncoders").encodeCreateSubscriptionRequest(writer, obj); break;
            case 788: require("./binaryEncoders").encodeCreateSubscriptionResponse(writer, obj); break;
            case 791: require("./binaryEncoders").encodeModifySubscriptionRequest(writer, obj); break;
            case 794: require("./binaryEncoders").encodeModifySubscriptionResponse(writer, obj); break;
            case 797: require("./binaryEncoders").encodeSetPublishingModeRequest(writer, obj); break;
            case 800: require("./binaryEncoders").encodeSetPublishingModeResponse(writer, obj); break;
            case 803: require("./binaryEncoders").encodeNotificationMessage(writer, obj); break;
            case 806: require("./binaryEncoders").encodeMonitoredItemNotification(writer, obj); break;
            case 809: require("./binaryEncoders").encodeDataChangeNotification(writer, obj); break;
            case 818: require("./binaryEncoders").encodeStatusChangeNotification(writer, obj); break;
            case 821: require("./binaryEncoders").encodeSubscriptionAcknowledgement(writer, obj); break;
            case 824: require("./binaryEncoders").encodePublishRequest(writer, obj); break;
            case 827: require("./binaryEncoders").encodePublishResponse(writer, obj); break;
            case 830: require("./binaryEncoders").encodeRepublishRequest(writer, obj); break;
            case 833: require("./binaryEncoders").encodeRepublishResponse(writer, obj); break;
            case 836: require("./binaryEncoders").encodeTransferResult(writer, obj); break;
            case 839: require("./binaryEncoders").encodeTransferSubscriptionsRequest(writer, obj); break;
            case 842: require("./binaryEncoders").encodeTransferSubscriptionsResponse(writer, obj); break;
            case 845: require("./binaryEncoders").encodeDeleteSubscriptionsRequest(writer, obj); break;
            case 848: require("./binaryEncoders").encodeDeleteSubscriptionsResponse(writer, obj); break;
            case 853: require("./binaryEncoders").encodeRedundantServerDataType(writer, obj); break;
            case 856: require("./binaryEncoders").encodeSamplingIntervalDiagnosticsDataType(writer, obj); break;
            case 859: require("./binaryEncoders").encodeServerDiagnosticsSummaryDataType(writer, obj); break;
            case 862: require("./binaryEncoders").encodeServerStatusDataType(writer, obj); break;
            case 865: require("./binaryEncoders").encodeSessionDiagnosticsDataType(writer, obj); break;
            case 868: require("./binaryEncoders").encodeSessionSecurityDiagnosticsDataType(writer, obj); break;
            case 871: require("./binaryEncoders").encodeServiceCounterDataType(writer, obj); break;
            case 874: require("./binaryEncoders").encodeSubscriptionDiagnosticsDataType(writer, obj); break;
            case 877: require("./binaryEncoders").encodeModelChangeStructureDataType(writer, obj); break;
            case 884: require("./binaryEncoders").encodeRange(writer, obj); break;
            case 887: require("./binaryEncoders").encodeEUInformation(writer, obj); break;
            case 891: require("./binaryEncoders").encodeAnnotation(writer, obj); break;
            case 894: require("./binaryEncoders").encodeProgramDiagnosticDataType(writer, obj); break;
            case 897: require("./binaryEncoders").encodeSemanticChangeStructureDataType(writer, obj); break;
            case 914: require("./binaryEncoders").encodeEventNotificationList(writer, obj); break;
            case 917: require("./binaryEncoders").encodeEventFieldList(writer, obj); break;
            case 920: require("./binaryEncoders").encodeHistoryEventFieldList(writer, obj); break;
            case 938: require("./binaryEncoders").encodeIssuedIdentityToken(writer, obj); break;
            case 948: require("./binaryEncoders").encodeAggregateConfiguration(writer, obj); break;
            case 7594: require("./binaryEncoders").encodeEnumValueType(writer, obj); break;
            case 8912: require("./binaryEncoders").encodeTimeZoneDataType(writer, obj); break;
            case 11216: require("./binaryEncoders").encodeModificationInfo(writer, obj); break;
            case 11217: require("./binaryEncoders").encodeHistoryModifiedData(writer, obj); break;
            case 11295: require("./binaryEncoders").encodeUpdateStructureDataDetails(writer, obj); break;
            case 11943: require("./binaryEncoders").encodeEndpointUrlListDataType(writer, obj); break;
            case 11944: require("./binaryEncoders").encodeNetworkGroupDataType(writer, obj); break;
            case 12079: require("./binaryEncoders").encodeAxisInformation(writer, obj); break;
            case 12080: require("./binaryEncoders").encodeXVType(writer, obj); break;
            case 12171: require("./binaryEncoders").encodeComplexNumberType(writer, obj); break;
            case 12172: require("./binaryEncoders").encodeDoubleComplexNumberType(writer, obj); break;
            case 12189: require("./binaryEncoders").encodeServerOnNetwork(writer, obj); break;
            case 12190: require("./binaryEncoders").encodeFindServersOnNetworkRequest(writer, obj); break;
            case 12191: require("./binaryEncoders").encodeFindServersOnNetworkResponse(writer, obj); break;
            case 12193: require("./binaryEncoders").encodeRegisterServer2Request(writer, obj); break;
            case 12194: require("./binaryEncoders").encodeRegisterServer2Response(writer, obj); break;
            case 12554: require("./binaryEncoders").encodeTrustListDataType(writer, obj); break;
            case 12755: require("./binaryEncoders").encodeOptionSet(writer, obj); break;
            case 12756: require("./binaryEncoders").encodeUnion(writer, obj); break;
            case 12891: require("./binaryEncoders").encodeMdnsDiscoveryConfiguration(writer, obj); break;
            case 14273: require("./binaryEncoders").encodePublishedVariableDataType(writer, obj); break;
            case 14523: require("./binaryEncoders").encodeDataSetMetaDataType(writer, obj); break;
            case 14524: require("./binaryEncoders").encodeFieldMetaData(writer, obj); break;
            case 14525: require("./binaryEncoders").encodeDataTypeDescription(writer, obj); break;
            case 14533: require("./binaryEncoders").encodeKeyValuePair(writer, obj); break;
            case 14593: require("./binaryEncoders").encodeConfigurationVersionDataType(writer, obj); break;
            case 14744: require("./binaryEncoders").encodeFieldTargetDataType(writer, obj); break;
            case 15005: require("./binaryEncoders").encodeSimpleTypeDescription(writer, obj); break;
            case 15006: require("./binaryEncoders").encodeUABinaryFileDataType(writer, obj); break;
            case 15007: require("./binaryEncoders").encodeBrokerConnectionTransportDataType(writer, obj); break;
            case 15434: require("./binaryEncoders").encodeBaseConfigurationDataType(writer, obj); break;
            case 15435: require("./binaryEncoders").encodeBaseConfigurationRecordDataType(writer, obj); break;
            case 15436: require("./binaryEncoders").encodeCertificateGroupDataType(writer, obj); break;
            case 15480: require("./binaryEncoders").encodeWriterGroupDataType(writer, obj); break;
            case 15487: require("./binaryEncoders").encodeStructureDescription(writer, obj); break;
            case 15488: require("./binaryEncoders").encodeEnumDescription(writer, obj); break;
            case 15502: require("./binaryEncoders").encodeNetworkAddressDataType(writer, obj); break;
            case 15510: require("./binaryEncoders").encodeNetworkAddressUrlDataType(writer, obj); break;
            case 15520: require("./binaryEncoders").encodeReaderGroupDataType(writer, obj); break;
            case 15528: require("./binaryEncoders").encodeEndpointType(writer, obj); break;
            case 15530: require("./binaryEncoders").encodePubSubConfigurationDataType(writer, obj); break;
            case 15532: require("./binaryEncoders").encodeDatagramWriterGroupTransportDataType(writer, obj); break;
            case 15534: require("./binaryEncoders").encodeDataTypeSchemaHeader(writer, obj); break;
            case 15538: require("./binaryEncoders").encodeConfigurationUpdateTargetType(writer, obj); break;
            case 15556: require("./binaryEncoders").encodeApplicationIdentityDataType(writer, obj); break;
            case 15557: require("./binaryEncoders").encodeEndpointDataType(writer, obj); break;
            case 15558: require("./binaryEncoders").encodeServerEndpointDataType(writer, obj); break;
            case 15559: require("./binaryEncoders").encodeSecuritySettingsDataType(writer, obj); break;
            case 15560: require("./binaryEncoders").encodeUserTokenSettingsDataType(writer, obj); break;
            case 15578: require("./binaryEncoders").encodePublishedDataSetDataType(writer, obj); break;
            case 15580: require("./binaryEncoders").encodePublishedDataSetSourceDataType(writer, obj); break;
            case 15581: require("./binaryEncoders").encodePublishedDataItemsDataType(writer, obj); break;
            case 15582: require("./binaryEncoders").encodePublishedEventsDataType(writer, obj); break;
            case 15597: require("./binaryEncoders").encodeDataSetWriterDataType(writer, obj); break;
            case 15598: require("./binaryEncoders").encodeDataSetWriterTransportDataType(writer, obj); break;
            case 15605: require("./binaryEncoders").encodeDataSetWriterMessageDataType(writer, obj); break;
            case 15609: require("./binaryEncoders").encodePubSubGroupDataType(writer, obj); break;
            case 15611: require("./binaryEncoders").encodeWriterGroupTransportDataType(writer, obj); break;
            case 15616: require("./binaryEncoders").encodeWriterGroupMessageDataType(writer, obj); break;
            case 15617: require("./binaryEncoders").encodePubSubConnectionDataType(writer, obj); break;
            case 15618: require("./binaryEncoders").encodeConnectionTransportDataType(writer, obj); break;
            case 15621: require("./binaryEncoders").encodeReaderGroupTransportDataType(writer, obj); break;
            case 15622: require("./binaryEncoders").encodeReaderGroupMessageDataType(writer, obj); break;
            case 15623: require("./binaryEncoders").encodeDataSetReaderDataType(writer, obj); break;
            case 15628: require("./binaryEncoders").encodeDataSetReaderTransportDataType(writer, obj); break;
            case 15629: require("./binaryEncoders").encodeDataSetReaderMessageDataType(writer, obj); break;
            case 15630: require("./binaryEncoders").encodeSubscribedDataSetDataType(writer, obj); break;
            case 15631: require("./binaryEncoders").encodeTargetVariablesDataType(writer, obj); break;
            case 15634: require("./binaryEncoders").encodeIdentityMappingRuleType(writer, obj); break;
            case 15635: require("./binaryEncoders").encodeSubscribedDataSetMirrorDataType(writer, obj); break;
            case 15645: require("./binaryEncoders").encodeUadpWriterGroupMessageDataType(writer, obj); break;
            case 15652: require("./binaryEncoders").encodeUadpDataSetWriterMessageDataType(writer, obj); break;
            case 15653: require("./binaryEncoders").encodeUadpDataSetReaderMessageDataType(writer, obj); break;
            case 15657: require("./binaryEncoders").encodeJsonWriterGroupMessageDataType(writer, obj); break;
            case 15664: require("./binaryEncoders").encodeJsonDataSetWriterMessageDataType(writer, obj); break;
            case 15665: require("./binaryEncoders").encodeJsonDataSetReaderMessageDataType(writer, obj); break;
            case 15667: require("./binaryEncoders").encodeBrokerWriterGroupTransportDataType(writer, obj); break;
            case 15669: require("./binaryEncoders").encodeBrokerDataSetWriterTransportDataType(writer, obj); break;
            case 15670: require("./binaryEncoders").encodeBrokerDataSetReaderTransportDataType(writer, obj); break;
            case 15901: require("./binaryEncoders").encodeSessionlessInvokeRequestType(writer, obj); break;
            case 16313: require("./binaryEncoders").encodeAdditionalParametersType(writer, obj); break;
            case 17467: require("./binaryEncoders").encodeDatagramConnectionTransportDataType(writer, obj); break;
            case 17548: require("./binaryEncoders").encodeEphemeralKeyType(writer, obj); break;
            case 17606: require("./binaryEncoders").encodeGenericAttributeValue(writer, obj); break;
            case 17607: require("./binaryEncoders").encodeGenericAttributes(writer, obj); break;
            case 17861: require("./binaryEncoders").encodeDecimalDataType(writer, obj); break;
            case 18593: require("./binaryEncoders").encodeActionTargetDataType(writer, obj); break;
            case 18594: require("./binaryEncoders").encodePublishedActionDataType(writer, obj); break;
            case 18597: require("./binaryEncoders").encodeActionMethodDataType(writer, obj); break;
            case 18648: require("./binaryEncoders").encodeSortRuleElement(writer, obj); break;
            case 18649: require("./binaryEncoders").encodeReadEventDetailsSorted(writer, obj); break;
            case 18793: require("./binaryEncoders").encodePublishedActionMethodDataType(writer, obj); break;
            case 18794: require("./binaryEncoders").encodeDtlsPubSubConnectionDataType(writer, obj); break;
            case 18806: require("./binaryEncoders").encodeRationalNumber(writer, obj); break;
            case 18807: require("./binaryEncoders").encodeVector(writer, obj); break;
            case 18808: require("./binaryEncoders").encodeThreeDVector(writer, obj); break;
            case 18809: require("./binaryEncoders").encodeCartesianCoordinates(writer, obj); break;
            case 18810: require("./binaryEncoders").encodeThreeDCartesianCoordinates(writer, obj); break;
            case 18811: require("./binaryEncoders").encodeOrientation(writer, obj); break;
            case 18812: require("./binaryEncoders").encodeThreeDOrientation(writer, obj); break;
            case 18813: require("./binaryEncoders").encodeFrame(writer, obj); break;
            case 18814: require("./binaryEncoders").encodeThreeDFrame(writer, obj); break;
            case 18953: require("./binaryEncoders").encodeLldpManagementAddressTxPortType(writer, obj); break;
            case 18954: require("./binaryEncoders").encodeLldpManagementAddressType(writer, obj); break;
            case 18955: require("./binaryEncoders").encodeLldpTlvType(writer, obj); break;
            case 19311: require("./binaryEncoders").encodeJsonNetworkMessage(writer, obj); break;
            case 19312: require("./binaryEncoders").encodeJsonDataSetMessage(writer, obj); break;
            case 19313: require("./binaryEncoders").encodeJsonDataSetMetaDataMessage(writer, obj); break;
            case 19314: require("./binaryEncoders").encodeJsonApplicationDescriptionMessage(writer, obj); break;
            case 19315: require("./binaryEncoders").encodeJsonServerEndpointsMessage(writer, obj); break;
            case 19316: require("./binaryEncoders").encodeJsonStatusMessage(writer, obj); break;
            case 19317: require("./binaryEncoders").encodeJsonPubSubConnectionMessage(writer, obj); break;
            case 19318: require("./binaryEncoders").encodeJsonActionMetaDataMessage(writer, obj); break;
            case 19319: require("./binaryEncoders").encodeJsonActionResponderMessage(writer, obj); break;
            case 19320: require("./binaryEncoders").encodeJsonActionNetworkMessage(writer, obj); break;
            case 19321: require("./binaryEncoders").encodeJsonActionRequestMessage(writer, obj); break;
            case 19322: require("./binaryEncoders").encodeJsonActionResponseMessage(writer, obj); break;
            case 19361: require("./binaryEncoders").encodeLogRecord(writer, obj); break;
            case 19745: require("./binaryEncoders").encodeLogRecordsDataType(writer, obj); break;
            case 19746: require("./binaryEncoders").encodeSpanContextDataType(writer, obj); break;
            case 19747: require("./binaryEncoders").encodeTraceContextDataType(writer, obj); break;
            case 19748: require("./binaryEncoders").encodeNameValuePair(writer, obj); break;
            case 20999: require("./binaryEncoders").encodeSessionlessInvokeResponseType(writer, obj); break;
            case 23468: require("./binaryEncoders").encodeAliasNameDataType(writer, obj); break;
            case 23497: require("./binaryEncoders").encodeReadAnnotationDataDetails(writer, obj); break;
            case 23498: require("./binaryEncoders").encodeCurrencyUnitType(writer, obj); break;
            case 23599: require("./binaryEncoders").encodeStandaloneSubscribedDataSetRefDataType(writer, obj); break;
            case 23600: require("./binaryEncoders").encodeStandaloneSubscribedDataSetDataType(writer, obj); break;
            case 23601: require("./binaryEncoders").encodeSecurityGroupDataType(writer, obj); break;
            case 23602: require("./binaryEncoders").encodePubSubConfiguration2DataType(writer, obj); break;
            case 23603: require("./binaryEncoders").encodeQosDataType(writer, obj); break;
            case 23604: require("./binaryEncoders").encodeTransmitQosDataType(writer, obj); break;
            case 23605: require("./binaryEncoders").encodeTransmitQosPriorityDataType(writer, obj); break;
            case 23608: require("./binaryEncoders").encodeReceiveQosDataType(writer, obj); break;
            case 23609: require("./binaryEncoders").encodeReceiveQosPriorityDataType(writer, obj); break;
            case 23612: require("./binaryEncoders").encodeDatagramConnectionTransport2DataType(writer, obj); break;
            case 23613: require("./binaryEncoders").encodeDatagramWriterGroupTransport2DataType(writer, obj); break;
            case 23614: require("./binaryEncoders").encodeDatagramDataSetReaderTransportDataType(writer, obj); break;
            case 23724: require("./binaryEncoders").encodeServiceCertificateDataType(writer, obj); break;
            case 23743: require("./binaryEncoders").encodeApplicationConfigurationDataType(writer, obj); break;
            case 23744: require("./binaryEncoders").encodeAuthorizationServiceConfigurationDataType(writer, obj); break;
            case 24033: require("./binaryEncoders").encodeProgramDiagnostic2DataType(writer, obj); break;
            case 24105: require("./binaryEncoders").encodePortableQualifiedName(writer, obj); break;
            case 24106: require("./binaryEncoders").encodePortableNodeId(writer, obj); break;
            case 24107: require("./binaryEncoders").encodeUnsignedRationalNumber(writer, obj); break;
            case 24281: require("./binaryEncoders").encodeUserManagementDataType(writer, obj); break;
            case 25220: require("./binaryEncoders").encodePriorityMappingEntryType(writer, obj); break;
            case 25269: require("./binaryEncoders").encodePublishedDataSetCustomSourceDataType(writer, obj); break;
            case 25270: require("./binaryEncoders").encodePubSubKeyPushTargetDataType(writer, obj); break;
            case 25519: require("./binaryEncoders").encodePubSubConfigurationRefDataType(writer, obj); break;
            case 25520: require("./binaryEncoders").encodePubSubConfigurationValueDataType(writer, obj); break;
            case 32285: require("./binaryEncoders").encodeTransactionErrorType(writer, obj); break;
            case 32421: require("./binaryEncoders").encodeBitFieldDefinition(writer, obj); break;
            case 32434: require("./binaryEncoders").encodeAnnotationDataType(writer, obj); break;
            case 32435: require("./binaryEncoders").encodeLinearConversionDataType(writer, obj); break;
            case 32438: require("./binaryEncoders").encodeQuantityDimension(writer, obj); break;
            case 32659: require("./binaryEncoders").encodeReferenceDescriptionDataType(writer, obj); break;
            case 32660: require("./binaryEncoders").encodeReferenceListEntryDataType(writer, obj); break;
            case 32799: require("./binaryEncoders").encodeReadEventDetails2(writer, obj); break;
            case 32824: require("./binaryEncoders").encodeHistoryModifiedEvent(writer, obj); break;
            default:
                throw new Error(`Binary encoder for id ${id} not found`);
        }
    }

    public static decode<T>(reader: BufferReader, id: number): T {
        switch (id) {
            case 29: return require("./binaryDecoders").decodeEnumeration(reader) as T;
            case 96: return require("./binaryDecoders").decodeRolePermissionType(reader) as T;
            case 97: return require("./binaryDecoders").decodeDataTypeDefinition(reader) as T;
            case 99: return require("./binaryDecoders").decodeStructureDefinition(reader) as T;
            case 100: return require("./binaryDecoders").decodeEnumDefinition(reader) as T;
            case 101: return require("./binaryDecoders").decodeStructureField(reader) as T;
            case 102: return require("./binaryDecoders").decodeEnumField(reader) as T;
            case 258: return require("./binaryDecoders").decodeNode(reader) as T;
            case 261: return require("./binaryDecoders").decodeObjectNode(reader) as T;
            case 264: return require("./binaryDecoders").decodeObjectTypeNode(reader) as T;
            case 267: return require("./binaryDecoders").decodeVariableNode(reader) as T;
            case 270: return require("./binaryDecoders").decodeVariableTypeNode(reader) as T;
            case 273: return require("./binaryDecoders").decodeReferenceTypeNode(reader) as T;
            case 276: return require("./binaryDecoders").decodeMethodNode(reader) as T;
            case 279: return require("./binaryDecoders").decodeViewNode(reader) as T;
            case 282: return require("./binaryDecoders").decodeDataTypeNode(reader) as T;
            case 285: return require("./binaryDecoders").decodeReferenceNode(reader) as T;
            case 296: return require("./binaryDecoders").decodeArgument(reader) as T;
            case 299: return require("./binaryDecoders").decodeStatusResult(reader) as T;
            case 304: return require("./binaryDecoders").decodeUserTokenPolicy(reader) as T;
            case 308: return require("./binaryDecoders").decodeApplicationDescription(reader) as T;
            case 312: return require("./binaryDecoders").decodeEndpointDescription(reader) as T;
            case 316: return require("./binaryDecoders").decodeUserIdentityToken(reader) as T;
            case 322: return require("./binaryDecoders").decodeUserNameIdentityToken(reader) as T;
            case 325: return require("./binaryDecoders").decodeX509IdentityToken(reader) as T;
            case 331: return require("./binaryDecoders").decodeEndpointConfiguration(reader) as T;
            case 338: return require("./binaryDecoders").decodeBuildInfo(reader) as T;
            case 344: return require("./binaryDecoders").decodeSignedSoftwareCertificate(reader) as T;
            case 349: return require("./binaryDecoders").decodeNodeAttributes(reader) as T;
            case 352: return require("./binaryDecoders").decodeObjectAttributes(reader) as T;
            case 355: return require("./binaryDecoders").decodeVariableAttributes(reader) as T;
            case 358: return require("./binaryDecoders").decodeMethodAttributes(reader) as T;
            case 361: return require("./binaryDecoders").decodeObjectTypeAttributes(reader) as T;
            case 364: return require("./binaryDecoders").decodeVariableTypeAttributes(reader) as T;
            case 367: return require("./binaryDecoders").decodeReferenceTypeAttributes(reader) as T;
            case 370: return require("./binaryDecoders").decodeDataTypeAttributes(reader) as T;
            case 373: return require("./binaryDecoders").decodeViewAttributes(reader) as T;
            case 376: return require("./binaryDecoders").decodeAddNodesItem(reader) as T;
            case 379: return require("./binaryDecoders").decodeAddReferencesItem(reader) as T;
            case 382: return require("./binaryDecoders").decodeDeleteNodesItem(reader) as T;
            case 385: return require("./binaryDecoders").decodeDeleteReferencesItem(reader) as T;
            case 389: return require("./binaryDecoders").decodeRequestHeader(reader) as T;
            case 392: return require("./binaryDecoders").decodeResponseHeader(reader) as T;
            case 395: return require("./binaryDecoders").decodeServiceFault(reader) as T;
            case 420: return require("./binaryDecoders").decodeFindServersRequest(reader) as T;
            case 423: return require("./binaryDecoders").decodeFindServersResponse(reader) as T;
            case 426: return require("./binaryDecoders").decodeGetEndpointsRequest(reader) as T;
            case 429: return require("./binaryDecoders").decodeGetEndpointsResponse(reader) as T;
            case 432: return require("./binaryDecoders").decodeRegisteredServer(reader) as T;
            case 435: return require("./binaryDecoders").decodeRegisterServerRequest(reader) as T;
            case 438: return require("./binaryDecoders").decodeRegisterServerResponse(reader) as T;
            case 441: return require("./binaryDecoders").decodeChannelSecurityToken(reader) as T;
            case 444: return require("./binaryDecoders").decodeOpenSecureChannelRequest(reader) as T;
            case 447: return require("./binaryDecoders").decodeOpenSecureChannelResponse(reader) as T;
            case 450: return require("./binaryDecoders").decodeCloseSecureChannelRequest(reader) as T;
            case 453: return require("./binaryDecoders").decodeCloseSecureChannelResponse(reader) as T;
            case 456: return require("./binaryDecoders").decodeSignatureData(reader) as T;
            case 459: return require("./binaryDecoders").decodeCreateSessionRequest(reader) as T;
            case 462: return require("./binaryDecoders").decodeCreateSessionResponse(reader) as T;
            case 465: return require("./binaryDecoders").decodeActivateSessionRequest(reader) as T;
            case 468: return require("./binaryDecoders").decodeActivateSessionResponse(reader) as T;
            case 471: return require("./binaryDecoders").decodeCloseSessionRequest(reader) as T;
            case 474: return require("./binaryDecoders").decodeCloseSessionResponse(reader) as T;
            case 477: return require("./binaryDecoders").decodeCancelRequest(reader) as T;
            case 480: return require("./binaryDecoders").decodeCancelResponse(reader) as T;
            case 483: return require("./binaryDecoders").decodeAddNodesResult(reader) as T;
            case 486: return require("./binaryDecoders").decodeAddNodesRequest(reader) as T;
            case 489: return require("./binaryDecoders").decodeAddNodesResponse(reader) as T;
            case 492: return require("./binaryDecoders").decodeAddReferencesRequest(reader) as T;
            case 495: return require("./binaryDecoders").decodeAddReferencesResponse(reader) as T;
            case 498: return require("./binaryDecoders").decodeDeleteNodesRequest(reader) as T;
            case 501: return require("./binaryDecoders").decodeDeleteNodesResponse(reader) as T;
            case 504: return require("./binaryDecoders").decodeDeleteReferencesRequest(reader) as T;
            case 507: return require("./binaryDecoders").decodeDeleteReferencesResponse(reader) as T;
            case 511: return require("./binaryDecoders").decodeViewDescription(reader) as T;
            case 514: return require("./binaryDecoders").decodeBrowseDescription(reader) as T;
            case 518: return require("./binaryDecoders").decodeReferenceDescription(reader) as T;
            case 522: return require("./binaryDecoders").decodeBrowseResult(reader) as T;
            case 525: return require("./binaryDecoders").decodeBrowseRequest(reader) as T;
            case 528: return require("./binaryDecoders").decodeBrowseResponse(reader) as T;
            case 531: return require("./binaryDecoders").decodeBrowseNextRequest(reader) as T;
            case 534: return require("./binaryDecoders").decodeBrowseNextResponse(reader) as T;
            case 537: return require("./binaryDecoders").decodeRelativePathElement(reader) as T;
            case 540: return require("./binaryDecoders").decodeRelativePath(reader) as T;
            case 543: return require("./binaryDecoders").decodeBrowsePath(reader) as T;
            case 546: return require("./binaryDecoders").decodeBrowsePathTarget(reader) as T;
            case 549: return require("./binaryDecoders").decodeBrowsePathResult(reader) as T;
            case 552: return require("./binaryDecoders").decodeTranslateBrowsePathsToNodeIdsRequest(reader) as T;
            case 555: return require("./binaryDecoders").decodeTranslateBrowsePathsToNodeIdsResponse(reader) as T;
            case 558: return require("./binaryDecoders").decodeRegisterNodesRequest(reader) as T;
            case 561: return require("./binaryDecoders").decodeRegisterNodesResponse(reader) as T;
            case 564: return require("./binaryDecoders").decodeUnregisterNodesRequest(reader) as T;
            case 567: return require("./binaryDecoders").decodeUnregisterNodesResponse(reader) as T;
            case 570: return require("./binaryDecoders").decodeQueryDataDescription(reader) as T;
            case 573: return require("./binaryDecoders").decodeNodeTypeDescription(reader) as T;
            case 577: return require("./binaryDecoders").decodeQueryDataSet(reader) as T;
            case 580: return require("./binaryDecoders").decodeNodeReference(reader) as T;
            case 583: return require("./binaryDecoders").decodeContentFilterElement(reader) as T;
            case 586: return require("./binaryDecoders").decodeContentFilter(reader) as T;
            case 589: return require("./binaryDecoders").decodeFilterOperand(reader) as T;
            case 592: return require("./binaryDecoders").decodeElementOperand(reader) as T;
            case 595: return require("./binaryDecoders").decodeLiteralOperand(reader) as T;
            case 598: return require("./binaryDecoders").decodeAttributeOperand(reader) as T;
            case 601: return require("./binaryDecoders").decodeSimpleAttributeOperand(reader) as T;
            case 604: return require("./binaryDecoders").decodeContentFilterElementResult(reader) as T;
            case 607: return require("./binaryDecoders").decodeContentFilterResult(reader) as T;
            case 610: return require("./binaryDecoders").decodeParsingResult(reader) as T;
            case 613: return require("./binaryDecoders").decodeQueryFirstRequest(reader) as T;
            case 616: return require("./binaryDecoders").decodeQueryFirstResponse(reader) as T;
            case 619: return require("./binaryDecoders").decodeQueryNextRequest(reader) as T;
            case 622: return require("./binaryDecoders").decodeQueryNextResponse(reader) as T;
            case 626: return require("./binaryDecoders").decodeReadValueId(reader) as T;
            case 629: return require("./binaryDecoders").decodeReadRequest(reader) as T;
            case 632: return require("./binaryDecoders").decodeReadResponse(reader) as T;
            case 635: return require("./binaryDecoders").decodeHistoryReadValueId(reader) as T;
            case 638: return require("./binaryDecoders").decodeHistoryReadResult(reader) as T;
            case 641: return require("./binaryDecoders").decodeHistoryReadDetails(reader) as T;
            case 644: return require("./binaryDecoders").decodeReadEventDetails(reader) as T;
            case 647: return require("./binaryDecoders").decodeReadRawModifiedDetails(reader) as T;
            case 650: return require("./binaryDecoders").decodeReadProcessedDetails(reader) as T;
            case 653: return require("./binaryDecoders").decodeReadAtTimeDetails(reader) as T;
            case 656: return require("./binaryDecoders").decodeHistoryData(reader) as T;
            case 659: return require("./binaryDecoders").decodeHistoryEvent(reader) as T;
            case 662: return require("./binaryDecoders").decodeHistoryReadRequest(reader) as T;
            case 665: return require("./binaryDecoders").decodeHistoryReadResponse(reader) as T;
            case 668: return require("./binaryDecoders").decodeWriteValue(reader) as T;
            case 671: return require("./binaryDecoders").decodeWriteRequest(reader) as T;
            case 674: return require("./binaryDecoders").decodeWriteResponse(reader) as T;
            case 677: return require("./binaryDecoders").decodeHistoryUpdateDetails(reader) as T;
            case 680: return require("./binaryDecoders").decodeUpdateDataDetails(reader) as T;
            case 683: return require("./binaryDecoders").decodeUpdateEventDetails(reader) as T;
            case 686: return require("./binaryDecoders").decodeDeleteRawModifiedDetails(reader) as T;
            case 689: return require("./binaryDecoders").decodeDeleteAtTimeDetails(reader) as T;
            case 692: return require("./binaryDecoders").decodeDeleteEventDetails(reader) as T;
            case 695: return require("./binaryDecoders").decodeHistoryUpdateResult(reader) as T;
            case 698: return require("./binaryDecoders").decodeHistoryUpdateRequest(reader) as T;
            case 701: return require("./binaryDecoders").decodeHistoryUpdateResponse(reader) as T;
            case 704: return require("./binaryDecoders").decodeCallMethodRequest(reader) as T;
            case 707: return require("./binaryDecoders").decodeCallMethodResult(reader) as T;
            case 710: return require("./binaryDecoders").decodeCallRequest(reader) as T;
            case 713: return require("./binaryDecoders").decodeCallResponse(reader) as T;
            case 722: return require("./binaryDecoders").decodeDataChangeFilter(reader) as T;
            case 725: return require("./binaryDecoders").decodeEventFilter(reader) as T;
            case 728: return require("./binaryDecoders").decodeAggregateFilter(reader) as T;
            case 734: return require("./binaryDecoders").decodeEventFilterResult(reader) as T;
            case 737: return require("./binaryDecoders").decodeAggregateFilterResult(reader) as T;
            case 740: return require("./binaryDecoders").decodeMonitoringParameters(reader) as T;
            case 743: return require("./binaryDecoders").decodeMonitoredItemCreateRequest(reader) as T;
            case 746: return require("./binaryDecoders").decodeMonitoredItemCreateResult(reader) as T;
            case 749: return require("./binaryDecoders").decodeCreateMonitoredItemsRequest(reader) as T;
            case 752: return require("./binaryDecoders").decodeCreateMonitoredItemsResponse(reader) as T;
            case 755: return require("./binaryDecoders").decodeMonitoredItemModifyRequest(reader) as T;
            case 758: return require("./binaryDecoders").decodeMonitoredItemModifyResult(reader) as T;
            case 761: return require("./binaryDecoders").decodeModifyMonitoredItemsRequest(reader) as T;
            case 764: return require("./binaryDecoders").decodeModifyMonitoredItemsResponse(reader) as T;
            case 767: return require("./binaryDecoders").decodeSetMonitoringModeRequest(reader) as T;
            case 770: return require("./binaryDecoders").decodeSetMonitoringModeResponse(reader) as T;
            case 773: return require("./binaryDecoders").decodeSetTriggeringRequest(reader) as T;
            case 776: return require("./binaryDecoders").decodeSetTriggeringResponse(reader) as T;
            case 779: return require("./binaryDecoders").decodeDeleteMonitoredItemsRequest(reader) as T;
            case 782: return require("./binaryDecoders").decodeDeleteMonitoredItemsResponse(reader) as T;
            case 785: return require("./binaryDecoders").decodeCreateSubscriptionRequest(reader) as T;
            case 788: return require("./binaryDecoders").decodeCreateSubscriptionResponse(reader) as T;
            case 791: return require("./binaryDecoders").decodeModifySubscriptionRequest(reader) as T;
            case 794: return require("./binaryDecoders").decodeModifySubscriptionResponse(reader) as T;
            case 797: return require("./binaryDecoders").decodeSetPublishingModeRequest(reader) as T;
            case 800: return require("./binaryDecoders").decodeSetPublishingModeResponse(reader) as T;
            case 803: return require("./binaryDecoders").decodeNotificationMessage(reader) as T;
            case 806: return require("./binaryDecoders").decodeMonitoredItemNotification(reader) as T;
            case 809: return require("./binaryDecoders").decodeDataChangeNotification(reader) as T;
            case 818: return require("./binaryDecoders").decodeStatusChangeNotification(reader) as T;
            case 821: return require("./binaryDecoders").decodeSubscriptionAcknowledgement(reader) as T;
            case 824: return require("./binaryDecoders").decodePublishRequest(reader) as T;
            case 827: return require("./binaryDecoders").decodePublishResponse(reader) as T;
            case 830: return require("./binaryDecoders").decodeRepublishRequest(reader) as T;
            case 833: return require("./binaryDecoders").decodeRepublishResponse(reader) as T;
            case 836: return require("./binaryDecoders").decodeTransferResult(reader) as T;
            case 839: return require("./binaryDecoders").decodeTransferSubscriptionsRequest(reader) as T;
            case 842: return require("./binaryDecoders").decodeTransferSubscriptionsResponse(reader) as T;
            case 845: return require("./binaryDecoders").decodeDeleteSubscriptionsRequest(reader) as T;
            case 848: return require("./binaryDecoders").decodeDeleteSubscriptionsResponse(reader) as T;
            case 853: return require("./binaryDecoders").decodeRedundantServerDataType(reader) as T;
            case 856: return require("./binaryDecoders").decodeSamplingIntervalDiagnosticsDataType(reader) as T;
            case 859: return require("./binaryDecoders").decodeServerDiagnosticsSummaryDataType(reader) as T;
            case 862: return require("./binaryDecoders").decodeServerStatusDataType(reader) as T;
            case 865: return require("./binaryDecoders").decodeSessionDiagnosticsDataType(reader) as T;
            case 868: return require("./binaryDecoders").decodeSessionSecurityDiagnosticsDataType(reader) as T;
            case 871: return require("./binaryDecoders").decodeServiceCounterDataType(reader) as T;
            case 874: return require("./binaryDecoders").decodeSubscriptionDiagnosticsDataType(reader) as T;
            case 877: return require("./binaryDecoders").decodeModelChangeStructureDataType(reader) as T;
            case 884: return require("./binaryDecoders").decodeRange(reader) as T;
            case 887: return require("./binaryDecoders").decodeEUInformation(reader) as T;
            case 891: return require("./binaryDecoders").decodeAnnotation(reader) as T;
            case 894: return require("./binaryDecoders").decodeProgramDiagnosticDataType(reader) as T;
            case 897: return require("./binaryDecoders").decodeSemanticChangeStructureDataType(reader) as T;
            case 914: return require("./binaryDecoders").decodeEventNotificationList(reader) as T;
            case 917: return require("./binaryDecoders").decodeEventFieldList(reader) as T;
            case 920: return require("./binaryDecoders").decodeHistoryEventFieldList(reader) as T;
            case 938: return require("./binaryDecoders").decodeIssuedIdentityToken(reader) as T;
            case 948: return require("./binaryDecoders").decodeAggregateConfiguration(reader) as T;
            case 7594: return require("./binaryDecoders").decodeEnumValueType(reader) as T;
            case 8912: return require("./binaryDecoders").decodeTimeZoneDataType(reader) as T;
            case 11216: return require("./binaryDecoders").decodeModificationInfo(reader) as T;
            case 11217: return require("./binaryDecoders").decodeHistoryModifiedData(reader) as T;
            case 11295: return require("./binaryDecoders").decodeUpdateStructureDataDetails(reader) as T;
            case 11943: return require("./binaryDecoders").decodeEndpointUrlListDataType(reader) as T;
            case 11944: return require("./binaryDecoders").decodeNetworkGroupDataType(reader) as T;
            case 12079: return require("./binaryDecoders").decodeAxisInformation(reader) as T;
            case 12080: return require("./binaryDecoders").decodeXVType(reader) as T;
            case 12171: return require("./binaryDecoders").decodeComplexNumberType(reader) as T;
            case 12172: return require("./binaryDecoders").decodeDoubleComplexNumberType(reader) as T;
            case 12189: return require("./binaryDecoders").decodeServerOnNetwork(reader) as T;
            case 12190: return require("./binaryDecoders").decodeFindServersOnNetworkRequest(reader) as T;
            case 12191: return require("./binaryDecoders").decodeFindServersOnNetworkResponse(reader) as T;
            case 12193: return require("./binaryDecoders").decodeRegisterServer2Request(reader) as T;
            case 12194: return require("./binaryDecoders").decodeRegisterServer2Response(reader) as T;
            case 12554: return require("./binaryDecoders").decodeTrustListDataType(reader) as T;
            case 12755: return require("./binaryDecoders").decodeOptionSet(reader) as T;
            case 12756: return require("./binaryDecoders").decodeUnion(reader) as T;
            case 12891: return require("./binaryDecoders").decodeMdnsDiscoveryConfiguration(reader) as T;
            case 14273: return require("./binaryDecoders").decodePublishedVariableDataType(reader) as T;
            case 14523: return require("./binaryDecoders").decodeDataSetMetaDataType(reader) as T;
            case 14524: return require("./binaryDecoders").decodeFieldMetaData(reader) as T;
            case 14525: return require("./binaryDecoders").decodeDataTypeDescription(reader) as T;
            case 14533: return require("./binaryDecoders").decodeKeyValuePair(reader) as T;
            case 14593: return require("./binaryDecoders").decodeConfigurationVersionDataType(reader) as T;
            case 14744: return require("./binaryDecoders").decodeFieldTargetDataType(reader) as T;
            case 15005: return require("./binaryDecoders").decodeSimpleTypeDescription(reader) as T;
            case 15006: return require("./binaryDecoders").decodeUABinaryFileDataType(reader) as T;
            case 15007: return require("./binaryDecoders").decodeBrokerConnectionTransportDataType(reader) as T;
            case 15434: return require("./binaryDecoders").decodeBaseConfigurationDataType(reader) as T;
            case 15435: return require("./binaryDecoders").decodeBaseConfigurationRecordDataType(reader) as T;
            case 15436: return require("./binaryDecoders").decodeCertificateGroupDataType(reader) as T;
            case 15480: return require("./binaryDecoders").decodeWriterGroupDataType(reader) as T;
            case 15487: return require("./binaryDecoders").decodeStructureDescription(reader) as T;
            case 15488: return require("./binaryDecoders").decodeEnumDescription(reader) as T;
            case 15502: return require("./binaryDecoders").decodeNetworkAddressDataType(reader) as T;
            case 15510: return require("./binaryDecoders").decodeNetworkAddressUrlDataType(reader) as T;
            case 15520: return require("./binaryDecoders").decodeReaderGroupDataType(reader) as T;
            case 15528: return require("./binaryDecoders").decodeEndpointType(reader) as T;
            case 15530: return require("./binaryDecoders").decodePubSubConfigurationDataType(reader) as T;
            case 15532: return require("./binaryDecoders").decodeDatagramWriterGroupTransportDataType(reader) as T;
            case 15534: return require("./binaryDecoders").decodeDataTypeSchemaHeader(reader) as T;
            case 15538: return require("./binaryDecoders").decodeConfigurationUpdateTargetType(reader) as T;
            case 15556: return require("./binaryDecoders").decodeApplicationIdentityDataType(reader) as T;
            case 15557: return require("./binaryDecoders").decodeEndpointDataType(reader) as T;
            case 15558: return require("./binaryDecoders").decodeServerEndpointDataType(reader) as T;
            case 15559: return require("./binaryDecoders").decodeSecuritySettingsDataType(reader) as T;
            case 15560: return require("./binaryDecoders").decodeUserTokenSettingsDataType(reader) as T;
            case 15578: return require("./binaryDecoders").decodePublishedDataSetDataType(reader) as T;
            case 15580: return require("./binaryDecoders").decodePublishedDataSetSourceDataType(reader) as T;
            case 15581: return require("./binaryDecoders").decodePublishedDataItemsDataType(reader) as T;
            case 15582: return require("./binaryDecoders").decodePublishedEventsDataType(reader) as T;
            case 15597: return require("./binaryDecoders").decodeDataSetWriterDataType(reader) as T;
            case 15598: return require("./binaryDecoders").decodeDataSetWriterTransportDataType(reader) as T;
            case 15605: return require("./binaryDecoders").decodeDataSetWriterMessageDataType(reader) as T;
            case 15609: return require("./binaryDecoders").decodePubSubGroupDataType(reader) as T;
            case 15611: return require("./binaryDecoders").decodeWriterGroupTransportDataType(reader) as T;
            case 15616: return require("./binaryDecoders").decodeWriterGroupMessageDataType(reader) as T;
            case 15617: return require("./binaryDecoders").decodePubSubConnectionDataType(reader) as T;
            case 15618: return require("./binaryDecoders").decodeConnectionTransportDataType(reader) as T;
            case 15621: return require("./binaryDecoders").decodeReaderGroupTransportDataType(reader) as T;
            case 15622: return require("./binaryDecoders").decodeReaderGroupMessageDataType(reader) as T;
            case 15623: return require("./binaryDecoders").decodeDataSetReaderDataType(reader) as T;
            case 15628: return require("./binaryDecoders").decodeDataSetReaderTransportDataType(reader) as T;
            case 15629: return require("./binaryDecoders").decodeDataSetReaderMessageDataType(reader) as T;
            case 15630: return require("./binaryDecoders").decodeSubscribedDataSetDataType(reader) as T;
            case 15631: return require("./binaryDecoders").decodeTargetVariablesDataType(reader) as T;
            case 15634: return require("./binaryDecoders").decodeIdentityMappingRuleType(reader) as T;
            case 15635: return require("./binaryDecoders").decodeSubscribedDataSetMirrorDataType(reader) as T;
            case 15645: return require("./binaryDecoders").decodeUadpWriterGroupMessageDataType(reader) as T;
            case 15652: return require("./binaryDecoders").decodeUadpDataSetWriterMessageDataType(reader) as T;
            case 15653: return require("./binaryDecoders").decodeUadpDataSetReaderMessageDataType(reader) as T;
            case 15657: return require("./binaryDecoders").decodeJsonWriterGroupMessageDataType(reader) as T;
            case 15664: return require("./binaryDecoders").decodeJsonDataSetWriterMessageDataType(reader) as T;
            case 15665: return require("./binaryDecoders").decodeJsonDataSetReaderMessageDataType(reader) as T;
            case 15667: return require("./binaryDecoders").decodeBrokerWriterGroupTransportDataType(reader) as T;
            case 15669: return require("./binaryDecoders").decodeBrokerDataSetWriterTransportDataType(reader) as T;
            case 15670: return require("./binaryDecoders").decodeBrokerDataSetReaderTransportDataType(reader) as T;
            case 15901: return require("./binaryDecoders").decodeSessionlessInvokeRequestType(reader) as T;
            case 16313: return require("./binaryDecoders").decodeAdditionalParametersType(reader) as T;
            case 17467: return require("./binaryDecoders").decodeDatagramConnectionTransportDataType(reader) as T;
            case 17548: return require("./binaryDecoders").decodeEphemeralKeyType(reader) as T;
            case 17606: return require("./binaryDecoders").decodeGenericAttributeValue(reader) as T;
            case 17607: return require("./binaryDecoders").decodeGenericAttributes(reader) as T;
            case 17861: return require("./binaryDecoders").decodeDecimalDataType(reader) as T;
            case 18593: return require("./binaryDecoders").decodeActionTargetDataType(reader) as T;
            case 18594: return require("./binaryDecoders").decodePublishedActionDataType(reader) as T;
            case 18597: return require("./binaryDecoders").decodeActionMethodDataType(reader) as T;
            case 18648: return require("./binaryDecoders").decodeSortRuleElement(reader) as T;
            case 18649: return require("./binaryDecoders").decodeReadEventDetailsSorted(reader) as T;
            case 18793: return require("./binaryDecoders").decodePublishedActionMethodDataType(reader) as T;
            case 18794: return require("./binaryDecoders").decodeDtlsPubSubConnectionDataType(reader) as T;
            case 18806: return require("./binaryDecoders").decodeRationalNumber(reader) as T;
            case 18807: return require("./binaryDecoders").decodeVector(reader) as T;
            case 18808: return require("./binaryDecoders").decodeThreeDVector(reader) as T;
            case 18809: return require("./binaryDecoders").decodeCartesianCoordinates(reader) as T;
            case 18810: return require("./binaryDecoders").decodeThreeDCartesianCoordinates(reader) as T;
            case 18811: return require("./binaryDecoders").decodeOrientation(reader) as T;
            case 18812: return require("./binaryDecoders").decodeThreeDOrientation(reader) as T;
            case 18813: return require("./binaryDecoders").decodeFrame(reader) as T;
            case 18814: return require("./binaryDecoders").decodeThreeDFrame(reader) as T;
            case 18953: return require("./binaryDecoders").decodeLldpManagementAddressTxPortType(reader) as T;
            case 18954: return require("./binaryDecoders").decodeLldpManagementAddressType(reader) as T;
            case 18955: return require("./binaryDecoders").decodeLldpTlvType(reader) as T;
            case 19311: return require("./binaryDecoders").decodeJsonNetworkMessage(reader) as T;
            case 19312: return require("./binaryDecoders").decodeJsonDataSetMessage(reader) as T;
            case 19313: return require("./binaryDecoders").decodeJsonDataSetMetaDataMessage(reader) as T;
            case 19314: return require("./binaryDecoders").decodeJsonApplicationDescriptionMessage(reader) as T;
            case 19315: return require("./binaryDecoders").decodeJsonServerEndpointsMessage(reader) as T;
            case 19316: return require("./binaryDecoders").decodeJsonStatusMessage(reader) as T;
            case 19317: return require("./binaryDecoders").decodeJsonPubSubConnectionMessage(reader) as T;
            case 19318: return require("./binaryDecoders").decodeJsonActionMetaDataMessage(reader) as T;
            case 19319: return require("./binaryDecoders").decodeJsonActionResponderMessage(reader) as T;
            case 19320: return require("./binaryDecoders").decodeJsonActionNetworkMessage(reader) as T;
            case 19321: return require("./binaryDecoders").decodeJsonActionRequestMessage(reader) as T;
            case 19322: return require("./binaryDecoders").decodeJsonActionResponseMessage(reader) as T;
            case 19361: return require("./binaryDecoders").decodeLogRecord(reader) as T;
            case 19745: return require("./binaryDecoders").decodeLogRecordsDataType(reader) as T;
            case 19746: return require("./binaryDecoders").decodeSpanContextDataType(reader) as T;
            case 19747: return require("./binaryDecoders").decodeTraceContextDataType(reader) as T;
            case 19748: return require("./binaryDecoders").decodeNameValuePair(reader) as T;
            case 20999: return require("./binaryDecoders").decodeSessionlessInvokeResponseType(reader) as T;
            case 23468: return require("./binaryDecoders").decodeAliasNameDataType(reader) as T;
            case 23497: return require("./binaryDecoders").decodeReadAnnotationDataDetails(reader) as T;
            case 23498: return require("./binaryDecoders").decodeCurrencyUnitType(reader) as T;
            case 23599: return require("./binaryDecoders").decodeStandaloneSubscribedDataSetRefDataType(reader) as T;
            case 23600: return require("./binaryDecoders").decodeStandaloneSubscribedDataSetDataType(reader) as T;
            case 23601: return require("./binaryDecoders").decodeSecurityGroupDataType(reader) as T;
            case 23602: return require("./binaryDecoders").decodePubSubConfiguration2DataType(reader) as T;
            case 23603: return require("./binaryDecoders").decodeQosDataType(reader) as T;
            case 23604: return require("./binaryDecoders").decodeTransmitQosDataType(reader) as T;
            case 23605: return require("./binaryDecoders").decodeTransmitQosPriorityDataType(reader) as T;
            case 23608: return require("./binaryDecoders").decodeReceiveQosDataType(reader) as T;
            case 23609: return require("./binaryDecoders").decodeReceiveQosPriorityDataType(reader) as T;
            case 23612: return require("./binaryDecoders").decodeDatagramConnectionTransport2DataType(reader) as T;
            case 23613: return require("./binaryDecoders").decodeDatagramWriterGroupTransport2DataType(reader) as T;
            case 23614: return require("./binaryDecoders").decodeDatagramDataSetReaderTransportDataType(reader) as T;
            case 23724: return require("./binaryDecoders").decodeServiceCertificateDataType(reader) as T;
            case 23743: return require("./binaryDecoders").decodeApplicationConfigurationDataType(reader) as T;
            case 23744: return require("./binaryDecoders").decodeAuthorizationServiceConfigurationDataType(reader) as T;
            case 24033: return require("./binaryDecoders").decodeProgramDiagnostic2DataType(reader) as T;
            case 24105: return require("./binaryDecoders").decodePortableQualifiedName(reader) as T;
            case 24106: return require("./binaryDecoders").decodePortableNodeId(reader) as T;
            case 24107: return require("./binaryDecoders").decodeUnsignedRationalNumber(reader) as T;
            case 24281: return require("./binaryDecoders").decodeUserManagementDataType(reader) as T;
            case 25220: return require("./binaryDecoders").decodePriorityMappingEntryType(reader) as T;
            case 25269: return require("./binaryDecoders").decodePublishedDataSetCustomSourceDataType(reader) as T;
            case 25270: return require("./binaryDecoders").decodePubSubKeyPushTargetDataType(reader) as T;
            case 25519: return require("./binaryDecoders").decodePubSubConfigurationRefDataType(reader) as T;
            case 25520: return require("./binaryDecoders").decodePubSubConfigurationValueDataType(reader) as T;
            case 32285: return require("./binaryDecoders").decodeTransactionErrorType(reader) as T;
            case 32421: return require("./binaryDecoders").decodeBitFieldDefinition(reader) as T;
            case 32434: return require("./binaryDecoders").decodeAnnotationDataType(reader) as T;
            case 32435: return require("./binaryDecoders").decodeLinearConversionDataType(reader) as T;
            case 32438: return require("./binaryDecoders").decodeQuantityDimension(reader) as T;
            case 32659: return require("./binaryDecoders").decodeReferenceDescriptionDataType(reader) as T;
            case 32660: return require("./binaryDecoders").decodeReferenceListEntryDataType(reader) as T;
            case 32799: return require("./binaryDecoders").decodeReadEventDetails2(reader) as T;
            case 32824: return require("./binaryDecoders").decodeHistoryModifiedEvent(reader) as T;
            default:
                throw new Error(`Binary decoder for id ${id} not found`);
        }
    }
}
