# This workflow publishes the package to npm when a release is created
name: Base Build

on:  
  workflow_dispatch:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    # Do not run on version-bump commits pushed by the release bot.
    if: github.actor != 'github-actions[bot]'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci
        working-directory: .

      - name: Verify
        run: npm run prepublish
        working-directory: packages/base
